kubeflow/testing

- images/Makefile
- images/checkout.sh
- images/version.json
- py/kubeflow/testing/test_util.py
- py/kubeflow/testing/test_util_test.py
- py/kubeflow/testing/util.py
* We need this for E2E testing because we will need to check out multiple
repositories. For example, to test our ksonnet configs we want to checkout
tensorflow/k8s so that we can run the tests defined within it.
* Move test_util from kubeflow/kubeflow to this repository so we can reuse it.
> checkout.sh should support checking out extra repositories.

- py/kubeflow/testing/github_status.py
- py/kubeflow/testing/run_e2e_workflow.py
Reasons for change:
- Would like a link directly from a PR to the corresponding argo workflow to make debugging easier
Changes made:
- Add calls to run_e2e_workflow.py for setting github status to pending, success, or failure
- Adds github_status.py for sending status update
> Add argo workflow status link

- images/Dockerfile
This is required for building and pushing serving containers in the workflows.
> install docker for testing image

- README.md
* Looks like some files moved in the kubeflow/test-infra repository
* Update instructions to reflect the fact that we now have our own org and webhooks can be set at the org level.
> Update instructions about adding a repository.

- images/Dockerfile
- images/Makefile
- images/run_workflows.sh
- py/kubeflow/testing/argo_client.py
- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/testing/run_e2e_workflow_test.py
- py/kubeflow/testing/util.py
* Currently each repository needs to build a new Docker container. The sole purpose of this container is to specify the path to the Argo workflow to run.
* We can simplify this by just allowing each repository to define a "prow_config.yaml" file at the root of the repository and then having a single binary which will read that config file and use it to figure out which workflows to invoke
* This fixes #24 
* We also add support for running multiple workflows.
* This will make it easy to start using prow to build our containers on each commit (#19)
> Support running multiple workflows and using a single entrypoint for prow jobs

- py/kubeflow/testing/run_e2e_workflow.py
* We were checking the wrong variable in the loop.
* This was a typo introduced when we switched to supporting multiple workflows.
Fix #30
> Fix syntax error that is causing prow jobs to exit with an error causing all tests to be reported as failures.

- .travis.yml
- images/Dockerfile
this is cherry-picked from #36 so that it can unblock others.
@jlewi but it seems the CLA status is blocking...
> Enable travis and do configurations

- py/kubeflow/testing/run_e2e_workflow.py
for now the `timeline` url path gave me a blank line everytime i want to access the build job. using `workflows` renders the correct result.
also the `tab` is a query (i.e. follows a `?`)
> fix argo uri

- py/kubeflow/testing/util.py
GPU deployment takes more time:
https://github.com/kubeflow/kubeflow/pull/442 failed, but the deployment actually succeeded.
> Make wait_for_deployment timeout configurable

- py/kubeflow/testing/prow_artifacts.py
- py/kubeflow/testing/prow_artifacts_test.py
- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/testing/run_e2e_workflow_test.py
- py/kubeflow/testing/test_util_test.py
- py/kubeflow/testing/util.py
- py/kubeflow/testing/util_test.py
* We want to be able to parameterize our E2E workflows and invoke them
with different parameters. For example, we want to use parameters to control
whether a test runs on minikube or GKE.
* To support this we need to add the ability to specify parameters to pass
to ksonnet as part of prow_config.yaml
* Improve metadata reported in Gubernator to make it easier to see results
for multiple workflows
* Have separate fields containing the UI URL for each workflow
* Also report the phase of each workflow in the metadata.
> Add the ability to specify arbitrary parameters in prow_config.yaml

- py/kubeflow/testing/prow_artifacts.py
- py/kubeflow/testing/run_e2e_workflow.py
finalize_prow_job returns the test result.
run_e2e_workflow.run returns False if there is failure. 
run_e2e_workflow will then exit(1) if there is failure.
/cc @jlewi 
Fix https://github.com/kubeflow/kubeflow/issues/436
> Check junit files for test status

- py/kubeflow/testing/util.py
* Don't wait for the process to finish to log the output.
* This is more convenient for streaming the output of long running commands.
* We no longer use Airflow so redirecting to a file and then reading that
file should no longer be necessary.
* Change run to also return output and have run_and_output should be a wrapper around run
* We can delete run_and_output after updating the callers.
> Poll for subprocess output while the process is running.

- images/Dockerfile
- images/Makefile
- py/kubeflow/testing/util.py
* We use ssh to execute code on the VM used for minikube.
* Modify the makefile to build the image so we can build without adding the latest tag. Gives us an
opportunity to debug it.
* Related to #6
> Add ssh for minikube testing.

- README.md
* Add information about debugging failed deployments by getting K8s events.
* Add information about using Stackdriver logging to get pod logs for prow
job.
* Fix #45
> Add information about debugging failed tests.

- README.md
- images/checkout.sh
- py/kubeflow/testing/util.py
- test-infra/components/debug-worker.jsonnet
* See kubernetes-client/python-base#54
* We need to provide userinfo.email scope to service accounts when with the K8s python client library.
* K8s server needs to know the email of the service account because RBAC role bindings can be expressed in terms of the email but without the userinfo.email scope it will end up using the numeric id
and we will get RBAC roles because of missing bindings.
* Update the debug worker to use the image in kubeflow-ci.
> Use userinfo.email scope with kube API Client

- images/Dockerfile
It was removed in https://github.com/kubeflow/testing/pull/36/files
Related https://github.com/kubeflow/testing/issues/112
/cc @pdmack 
/cc @lluunn
> Add ssh to test-worker

- py/kubeflow/testing/util.py
Currently this does not work with python3
/cc @inc0
Similar to https://github.com/kubeflow/kubeflow/pull/759#pullrequestreview-117579486
> Fix bytes literals in run() command

- py/kubeflow/testing/util.py
function wait_for_deployment may now check custom number of replicas running
Needed for https://github.com/kubeflow/kubeflow/issues/346 , as we may want to verify that all 3 replicas are Running
> Added optional param replicas

- py/kubeflow/testing/run_e2e_workflow.py
show up in build-log.txt reported to Gubernator.
Related to #125 
/assign @pdmack
> Catch arbitrary exceptions in wait_for_workflows and log them so they

- images/Dockerfile
ref: https://github.com/kubeflow/kubeflow/pull/837#issuecomment-390719872
I updated ksonnet version to 0.10.2 in Docker image used by our E2E tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/134)
> upgrade ksonnet to 0.10.2 in e2e Docker image

- README.md
* Add link to strackdriver logs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/138)
> Add a link to stackdriver logging for prow jobs to make it easier to get to the logs

- dev-kubeflow-org/ks-app/components/issue-summarization-ui.jsonnet
- dev-kubeflow-org/ks-app/components/params.libsonnet
* Issue Summarization UI service should be of type node port
* UI should also get GITHUB_TOKEN from a secret
* It looks like isssue-summarization-ui.jsonnet might have been signficantly
out of date
* There was no ingress to expose it publicly
* Doesn't look like namespace was set correctly
Fix kubeflow/examples#118 gh-demo.kubeflow.org down
Fix kubeflow/kubeflow#871 envoy crash looping because ingress not created
/assign @ankushagarwal 
/assign @pdmack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/140)
> Fix gh-demo.kubeflow.org

- py/kubeflow/testing/argo_client.py
A lot of workflows have been flaky because of this exception.
```
ERROR|2018-06-06T21:31:19|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|210| Exception occurred: 'status'
Traceback (most recent call last):
File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 196, in run
status_callback=argo_client.log_status)
File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
return Retrying(*dargs, **dkw).call(f, *args, **kw)
File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 212, in call
raise attempt.get()
File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 247, in get
six.reraise(self.value[0], self.value[1], self.value[2])
File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 200, in call
attempt = …
```
> Ignore KeyError exception in argo_client.log_status

- py/kubeflow/testing/argo_client.py
Sometimes it takes a while for the argo controller to populate
the status field of an object.
Fixes https://github.com/kubeflow/testing/issues/147
/assign @lluunn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/153)
> Check if status and phase is set in argo workflow crd

- images/Dockerfile
* We run multiple tests in parallel that are modifying the ksonnet app directory
I think this is leading to conflicts. So we want to use the filelock
as a simple inter process communication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/164)
> Add the filelock module.

- py/kubeflow/testing/run_e2e_workflow.py
* In kubeflow/kubeflow#1109 We are seeing lots of timeouts waiting for the
test workflows too complete.
* Bump the timeout to 1 hour.
* Related to #166
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/167)
> Increase the timeout waiting for workflows to finish.

- py/kubeflow/testing/argo_client.py
* We were using a fixed retry window that was too short O(5 seconds).
* Use exponential backoff and retry for up to 3 minutes. We are seeing
test flakes due to problems getting the workflow status.
* Related to #169
/assign @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/170)
> Use exponential backoff when getting the workflow status.

- py/kubeflow/testing/argo_client.py
* We are seeing lots of test flakes doing to temporary problems connecting
to the K8s master.
Related to #169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/172)
> Increase the timeout when waiting for the workflows to 20 minutes.

- README.md
* We want to set the resource type to container because we are interested in
container logs.
/assign @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/178)
> Fix the stackdriver link.

- py/kubeflow/testing/prow_artifacts.py
- workflows/components/workflows.libsonnet
* See kubeflow/tf-operator#748
* A test can run multiple instances of a workflow but with different parameters.
* In this case we need to make sure the junit files and other artifacts
copied to GCS for gubernator have unique names.
* One way to make this easier is to have copy-artifacts automatically
append a unique suffix to each file before copying it to GCS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/183)
> Copy artifacts should make the file names unique by appending a suffix.

- py/kubeflow/testing/test_helper.py
* This is intended to help debug kubeflow/kubeflow#1426 by showing whether
generate_xml is called.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/197)
> Log a message when producing the XML file.

- py/kubeflow/testing/test_helper.py
* name is used in the XMl file containing the test results. If name
isn't set the XML file won't be created correctly and therefore
not surfaced in gubernator correctly; see kubeflow/kubeflow#1426
* Related to kubeflow/kubeflow#1426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/198)
> Require name to be set for TestSuite.

- py/kubeflow/testing/run_e2e_workflow.py
* The namespace argument is useful when running the release workflows manually
to test them.
Related to kubeflow/kubeflow#1541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/203)
> Add a namespace argument

- release-infra/kubeflow-images-public.iam.policy.yaml
* This is a temporary solution to improve automation around releasing our
images by pushing them on postsubmit.
* See
kubeflow/kubeflow#1574 use prow to auto release images
kubeflow/kubeflow#816 trigger image pushes on postsubmit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/211)
> Grant permissions to test service account to push to our public registry

- label_sync/kubeflow_label.yml
adding ability for new users to add label to open issues to an area for release 0.4.0
Related to: kubeflow/community#173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/200)
> Adding label for 0.4.0 as area/0.4.0

- py/kubeflow/testing/argo_client.py
- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/testing/util.py
- py/kubeflow/tests/argo_client_test.py
This is a work around for kubernetes-client/python-base#59
There is a bug in the python K8s client preventing GCP auth tokens from being refreshed when they expire.
* As a result our E2E tests fail waiting for workflows that take more than an hour. In this case, the OAuth token expires so the requests to get workspace status fail with unauthorized 
see
#207  - Argo client should refresh credentials if OAuth token expires
#204 - argo_client doesn't handle retries correctly.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/215)
> Recreate k8s client on auth failure

- py/kubeflow/testing/run_e2e_workflow.py
Recently we added presubmit and postsubmit workflows to build Docker images. Some of them can take over 2 hours to build, so we need to increase the timeout in our e2e workflows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/216)
> Increase timeout in E2E workflow from 1 to 3 hours

- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/testing/util.py
For https://github.com/kubeflow/kubeflow/issues/1617
Also add logs to describe the deployment when timeout waiting for it.
/cc @richardsliu @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/217)
> Add log for why triggering a workflow

- README.md
- py/kubeflow/testing/run_e2e_workflow.py
Previously the "include_dirs" parameter in prow_config for scoping workflows is only considered for presubmit jobs. Recently we've added postsubmit jobs that build/push Docker images, and these can be time/resource-consuming. This change adds scoping abilities to postsubmit jobs, using the command
`git diff --name-only HEAD^ HEAD` to compare against the last commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/218)
> Enable workflow scoping for postsubmit jobs

- images/checkout.sh
This change allows checkout.sh to checkout a branch (e.g. v0.3-branch) on a repository. This is to allow periodic Prow jobs to run against specific release branches.
A separate PR will be made to pass in the environment variables for periodic jobs.
Related to #214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/219)
> Allow checkout.sh to process branch name

- images/checkout.sh
- py/kubeflow/testing/run_e2e_workflow.py
For postsubmit jobs, we can detect the list of changed files by doing
```
git diff --name-only PULL_BASE_SHA^ PULL_BASE_SHA
```
Where PULL_BASE_SHA is set by the Prow environment.
Also added more logging for debugging purposes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/223)
> Compute postsubmit file diffs by PULL_BASE_SHA

- images/checkout.sh
- py/kubeflow/testing/run_e2e_workflow.py
For periodic Prow jobs, we should run all the test workflows whose job_type includes "periodic". We should not consider modified_dirs since there is no last commit hash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/226)
> Don't consider modified_dirs for periodic jobs

- images/Dockerfile
- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/tests/run_e2e_workflow_test.py
- Install both ks 0.11 and 0.12 in the docker image for test-worker
- "ks" points to 0.11, "ks-12" points to 0.12
- By default, test-worker uses ks 0.11
- Run_e2e_workflow determines which version of ks to use by examining app_dir/app.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/228)
> Allow run_e2e_workflow to select which version of ks to use

- deployment/kubeflow-latest_ks_app/vendor/kubeflow/katib@177377f154475e797ebf2c9bb7d156862f8e1231/prototypes/all.jsonnet
- py/kubeflow/testing/prow_artifacts.py
- py/kubeflow/tests/prow_artifacts_test.py
Prow artifacts were not being uploaded to GCS correctly. This is because we recently added environment variables for repo name and owner. The fix is to determine the GCS path based on job_type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/230)
> Fix gcs directory path for periodic Prow jobs

- label_sync/cluster/label_sync_cron_job.yaml
- label_sync/cluster/label_sync_job.yaml
- label_sync/kubeflow_label.yml
* The docker image needs to be updated to the latest image to fix the
crash.
* The YAML config changed and needed to be updated in order to sync properly.
* Rename release/ to area/ so that it can be applied with the bot.
Related to kubeflow/community#173
* Rename label testing to area/testing so that it can be applied with the bot
* Rename problem/bug to kind/bug so that it can be applied with the bot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/224)
> Fix the label sync

- label_sync/README.md
- label_sync/cluster/label_sync_job.yaml
- label_sync/kubeflow_label.yml
* The indentation in kubeflow_label.yml was messed up so the 0.4.0
tag wasn't being included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/232)
> Fix label 0.4.0

- py/kubeflow/testing/util.py
Use this version of the driver installer daemonset: https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#installing_drivers
Tried this on a test cluster manually and it seems to fix the GPU pool problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/246)
> Use daemonset-preloaded yaml

- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/tests/run_e2e_workflow_test.py
* We need to find the common ancestor between the pull request and the master
branch.
* We only want to consider files changed in the PR branch relative to the
common ancestor. If we just compare to the master branch we end up
including files that were changed on the master branch since the commit
on which the PR was based. This is undesirable because we will end up
triggering tests unrelated to the PR.
Related to kubeflow/testing#229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/255)
> Properly compute the changed files in presubmits.

- images/Dockerfile
- py/kubeflow/testing/ks_util.py
Add support ksonnet 0.3.0 apps in our test image.  …
* Install ksonnet 0.13.
* If the app spec is 0.3.0 then ks_util.get_command should use ks-13.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/274)
> Support ksonnet apps using 0.3.0 spec in our tests.

- label_sync/kubeflow_label.yml
The mentioned labels are very close to the threshold that github uses to determine whether to use black or white foreground text.
By darkening them slightly, the foreground switches to white, and the labels become more readable.
Before:
After:
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/241)
> Improve readability of priority/p1 and status/icebox labels

- label_sync/kubeflow_label.yml
* Define some CUJ labels to begin grouping issues by CUJ. This will
be a good way to group issues across repos and relate them to releases.
* kubernetes/test-infra#10515 will allow the prow bot to set labels
/community, /platform, /cuj so all members will be able to begin
setting those labels.
* Add a label for community mainenance.
* Remove os labels we aren't using them
* Remove problems label these aren't using them.
* Remove improvemnt labels these aren't using them
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/253)
> Add labels for CUJs and cleanup some labels.

- py/kubeflow/testing/util.py
* It looks like on python3 util.run keeps polling for the end of stdout
becase we don't treat the final line as a byte string e.g b''.
* Need to decode some strings in python3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/281)
> Make util.run py3 compatible.

- py/kubeflow/testing/prow_artifacts.py
- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/tests/prow_artifacts_test.py
* We want gubernator to surface Argo UI URLs when the test starts rather
than having to wait until it finishes.
* We do this by including the links in the started.json metadata.
* This will be surfaced in gubernator until finished.json is created.
Fix #82
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/291)
> Show Argo workflow URLs when test starts.

- py/kubeflow/testing/cleanup_ci.py
* Use the changes in kubeflow/kubeflow#2344; specify command line arguments
for delete_deployment.sh by name not position
* Get the zone from the deployment manifest
* kubeflow/kubeflow#2344 doesn't depend on iam_patch.yaml; instead it
loos for bindings with the specified name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/293)
> Improve the cleanup of Kubeflow deployments.

- deployment/redeploy_app.sh
- and improved syntax
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/285)
> Fixed missing quotes in echo statement

- py/kubeflow/testing/cleanup_ci.py
- test-infra/ks_app/components/cleanup-ci-cron.jsonnet
- test-infra/ks_app/components/cleanup-ci.jsonnet
- test-infra/ks_app/components/cleanup-ci.libsonnet
- test-infra/ks_app/components/params.libsonnet
* Add to cleanup_ci.py an "all" subcommand to delete all resources."
* Add a batch job for one off runs.
Related to:
Fix  #87 Cron job to garbage collect test resources
Fix  #249 cron job to collect Kubeflow deployments launched by E2E tests
Fix #53 GC Argo workflows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/300)
> Create a cron job to regularly garbage collect test resources.

- images/Dockerfile
We need 1.11 to build bootstrapper which is using go modules.
/cc @kunmingg 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/303)
> upgrade test worker to go1.11

- images/Makefile
- images/gcb_build/image_build.json
- images/image_build.jsonnet
Fix #304 
* the image built was gcr.io/kubeflow-ci/test-worker/test-worker:TAG (two test-worker)
* the generated dir, `build`, will make local `make build` do nothing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/305)
> fix gcb issue

- images/Dockerfile
- images/gcb_build/image_build.json
See https://github.com/kubeflow/kubeflow/issues/2364#issuecomment-461558025
Bootstrap now has a dependency that needs to be cloned by hg
/cc @kunmingg 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/307)
> add mercurial to test image

- README.md
* We upgraded the test cluster to use the new stackdriver monitoring
to make it easier to monitor Kubeflow.
* This PR updates the readme to provide instructions on how to leverage that.
* Fix #177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/309)
> Document how to Use the new stackdriver agents in our test cluster.

- test-infra/auto-deploy/deploy-cron.yaml
Current format is every 8 minutes, changed the spec to be every 8 hours.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/312)
> Fix cron format

- py/kubeflow/__init__.py
To resolve [this issue](https://github.com/kubeflow/tf-operator/issues/914) we followed instructions at [python package namespacing](https://packaging.python.org/guides/packaging-namespace-packages/) to adopt pkgutil namespacing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/322)
> Adopting Python pkgutil-style namespacing

- test-infra/auto-deploy/deploy-cron-v0-4.yaml
* The v0.4-branch should be specified on the kubeflow/kubeflow repo
not the testing repo.
Related to #315
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/327)
> Fix repo spec for 0.4 auto-deploy cron job.

- playbook.md
- py/kubeflow/testing/cleanup_ci.py
- test-infra/ks_app/components/cleanup-ci.libsonnet
* Add a playbook and describe how to deal with the CI infrastructure running
out of GCP quota.
* The cron/batch job for the CI system should not be pinned to checkout
the code at PR 300; we should be using master.
* We are seeing socket errors contacting the DM service so add some retries
and in the event of permanent failure try to keep going.
Related to: #337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/338)
> Add a playbook for dealing with cleaning up the test infrastructure.

- py/kubeflow/testing/cleanup_ci.py
1. Fix a typo in the code which causes exception:
```
File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
return Retrying(*dargs, **dkw).call(f, *args, **kw)
TypeError: __init__() got an unexpected keyword argument 'stop_max_attempt'
```
2. Make all cleanup operations best effort: a failure of one will not block the following operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/340)
> Fix cleanup_ci exception

- py/kubeflow/testing/cleanup_ci.py
- py/kubeflow/testing/create_kf_instance.py
- test-infra/auto-deploy/deploy-cron-v0-5.yaml
- test-infra/auto-deploy/deploy-master.yaml
- test-infra/ks_app/components/cleanup-ci-cron.jsonnet
- test-infra/ks_app/components/cleanup-ci.jsonnet
- test-infra/ks_app/components/cleanup-ci.libsonnet
* Move auto-deployments into project kubeflow-ci-deployment.
* Fix a bug in cleanup_ci.py; we were not properly handling the case where there was no manifest in the deployment.
* Update cleanup ci cron jobs to run in two projects
kubeflow-ci and kubeflow-ci-deployment.
* Create a cron job for auto deploying 0.5
* Update the cron job for auto-deploying master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/344)
> Update auto-deploy infrastructure to use the new kfctl binary.

- py/kubeflow/testing/create_kf_instance.py
- test-infra/auto-deploy/auto_deploy.sh
- test-infra/auto-deploy/deploy-cron-master.yaml
- test-infra/auto-deploy/deploy-cron-v0-5.yaml
Fixes #350
Updates with this PR:
1. Adds back labels to clusters.
1. Use `CLIENT_ID/CLIENT_SECRET` from kubeflow-ci-deployment.
1. Fixes base name for v0-5 cronjobs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/352)
> Update cronjob to deploy testing clusters to kubeflow-ci-deployment

- py/kubeflow/testing/create_kf_instance.py
Deletion to endpoint service is in soft-deletion and will be purged after 30 days.  If a service is trying to re-use the same endpoint that is in soft-deletion, it will be an error.  Need to undelete it so that endpoint-controller can finish its job.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/353)
> Undelete endpoint service for testing cluster.

- OWNERS
- images/Dockerfile
- images/gcb_build/image_build.json
- py/kubeflow/testing/cleanup_ci.py
- test-infra/ks_app/components/cleanup-ci.libsonnet
Fix cleanup_ci.py - cleaning of Argo and service account binding
* Add logging to make it easier to monitor progress.
* Print out stack traces on errors.
* cleanup_workflows needs to get GKE credentials.
* The project might be different from the project where KF is deployed.
Related to #358 cleanup ci not cleaning up Argo workflows
Related to #357 cleanup ci not cleaning up IAM policies.
* Fix bug in cleaning up Argo workflows; we should not break out of loop.
* Don't exit if delete of Workflow fails; it looks like there might be
some race conditions.
* Update the docker image to use google-api-python-client library 1.7.0 instead
of 1.6.5. It looks like using 1.6.5 gives us an error when getting IAM
policy.
* Prune the OWNERs file to remove a bunch of approvers who haven't been active. …
> Fix cleanup_ci.py - fix cleanup of argo workflows and IAM policy bindings

- py/kubeflow/testing/cleanup_ci.py
* Argo workflows were being GC'd after 3 hours like other resources. That is
too aggressive. We want the workflows to be around longer to aid debugging.
* Fix 362
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/363)
> Argo workflows's should stick around for a week or so.

- images/Dockerfile
- images/Makefile
- images/checkout_repos.sh
- images/gcb_build/image_build.json
- images/setup_ssh.sh
- py/kubeflow/__init__.py
- py/kubeflow/testing/test_py_lint.py
Add fire, gitpython and hub to test image, fix namespace packaging.
* fire is a python library that makes it easy to define entrypoints
* gitpython is a python library for git; this will be used for gitops and CI/CD
* hub is a CLI for github that will be used for gitops
* Create a script to checkout repos. This is intended to be used in
situations where we want to check out the latest code and then run some
script.
* Fix a bug in namespace package __init__.py has a typo.
* Parameterize the makefile for the worker image so that we can build the worker image for project kubeflow-releasing using GCB.
* Add a script for configuring permissions on ssh keys.
* This can be used in an init container to setup ssh keyes;
see
https://github.com/jlewi/kubeflow-dev/blob/master/notes/git_on_kubeflow.md …
> Add fire, gitpython and hub to test image and fix namespace packaging

- images/Dockerfile
Since updated the mnist examples to replace `ksonnet` with `kustomize`, to auto test the code changes, the `gcr.io/kubeflow-ci/test-worker/test-worker` need to be updated to install `kustomize`, so that command can be executed normally.
The PR is to update Dockerfile of the image, thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/370)
> add kustomize for test_worker image

- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/tests/run_e2e_workflow_test.py
**Background**
This fixes #375.
**Changes**
Used `PULL_BASE_REF` to get the base branch name and get a common ancestor for the PR and the base branch.
**Tests**
In Progress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/378)
> Use the injected base branch env var

- py/kubeflow/testing/argo_client.py
- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/tests/run_e2e_workflow_test.py
**Background**
This fixes https://github.com/kubeflow/testing/issues/374.
**Changes**
Now `wait_for_workflows` returns a tuple indicating whether we are returning because the function times out. Then we store the returned `results` in `workflow_status_yamls` and uploads to GCS anyways.
**Tests**
In Progress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/377)
> Upload workflow status while timeout

- py/kubeflow/testing/cleanup_ci.py
- test-infra/ks_app/components/cleanup-ci-cron.jsonnet
- test-infra/ks_app/components/cleanup-ci.libsonnet
#361 
Clean up backend services older than 24 hours in kubeflow-ci-deployment. The health checks related to the backend service will be cleaned up by existing `cleanup_health_checks` function.
/cc @jlewi @gabrielwen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/382)
> GC backend services in kubeflow-ci-deployment

- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/tests/run_e2e_workflow_test.py
**Background**
In https://github.com/kubeflow/kubeflow/pull/3216, @gabrielwen is observing error messages like ```fatal: Not a valid object name v0.5-branch``` in the presubmit tests.
This is because I was doing things like `git merge-base HEAD v0.5-branch` in https://github.com/kubeflow/testing/pull/378, e.g.
```
~/src/kubeflow/kubeflow master
❯ git merge-base HEAD v0.5-branch
fatal: Not a valid object name v0.5-branch
```
Instead we should do:
```
~/src/kubeflow/kubeflow v0.5-branch
❯ git merge-base HEAD remotes/origin/v0.4-branch
d48e22b2f7d7b80e14c5a07bf171f358b9f91131
```
**Changes**
* Added `remotes/origin` before the branch name in `git merge-base`
**Tests**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Fetch remote branches in E2E test

- OWNERS
The ONWERS file https://github.com/kubeflow/testing/blob/master/py/kubeflow/OWNERS doesn't work. So add us to the top level OWNERS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/389)
> Add  gabrielwen  & zhenghuiwang to OWNERS

- py/kubeflow/testing/cleanup_ci.py
* If a deployment is in error state; we want to clean it up pretty quickly
and not wait several hours.
* The problem is if deployments start failing because of quota issues
these will stack up and we may not recover. But if we aggresively
delete failed deployments this should help.
* Related to #391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/392)
> Aggressively cleanup failed deployments.

- py/kubeflow/testing/cleanup_ci.py
* We weren't properly paginating through the results; we need to reset
nextPageToken when switching zones
* Due to this bug cleanup_disks wasn't actually being called we were just
error'ing out and cleanup_ci was ignoring this error.
* We weren't calling execute on the delete request
* We needed more regexes to match disks to be deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/397)
> Fix cleanup disks

- py/kubeflow/testing/argo_client.py
* It looks like ApiException doesn't always store the HttpStatus code in .status
in some cases it will be stored in the body
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/398)
> Fix retry on gateway timeout (#306)

- images/Dockerfile
Add `cmake` to compile C++ dependencies for Kubeflow metadata server build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/399)
> Add cmake to testing worker image

- py/kubeflow/testing/argo_client.py
- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/testing/util.py
- py/kubeflow/tests/run_e2e_workflow_test.py
**Background**
This PR should fix https://github.com/kubeflow/testing/issues/386.
**Changes**
* Created a new exception type `ExceptionWithWorkflowResults` and I'm now using this type to reraise internal exceptions and store the most recent set of workflow results.
* Used the status code defined in `httplib` instead of manually defining status codes.
**Tests**
Not Applicable.
BTW, @jlewi One issue I'm seeing these days is right now there seems to be no easy way to locally validate our changes in this repo. Do you expect in the long term there shouldn't be that many changes in the testing repo so it's OK doing things this way or we should probably write some docs or find ways to make the changes easier to be tested?
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> Add a custom exception wrapping workflow results

- images/Dockerfile
Need Java runtime to use [OpenAPI generator](https://github.com/OpenAPITools/openapi-generator#1---installation) to generate OpenAPI client on the fly during metadata e2e test. https://github.com/kubeflow/metadata/issues/28
Tested locally:
```
root@8aef64b69411:/# java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/410)
> Add JDK8 to testing worker image

- images/checkout.sh
- images/checkout_repos.sh
Postsubmit is comparing the current commit with the previous commit, e.g.
```
git diff --name-only 56fafa45e96c7933eecf09d8174e993d778f41ec^ 56fafa45e96c7933eecf09d8174e993d778f41ec
```
So we need to have depth>1.
/cc @abhi-g @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/414)
> Fix postsubmit

- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/tests/run_e2e_workflow_test.py
Otherwise any non-master branch ends up `FETCH_HEAD`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/419)
> set refs for newly fetched remote branch

- images/checkout.sh
Fixes broken periodic tests like this one: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-periodic-0-6-branch/1157052862841229312/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/430)
> Fix periodic tests checkout script

- py/kubeflow/testing/create_kf_instance.py
- py/kubeflow/testing/util.py
- test-infra/auto-deploy/auto_deploy.sh
- test-infra/auto-deploy/deploy-cron-master.yaml
- test-infra/auto-deploy/deploy-cron-v0-6.yaml
- test-infra/auto-deploy/deploy-master.yaml
* Auto deployment from master should use --config flag to initialize KfDef
* I think we are pulling in outdated configs which is why master deployment
isn't working
* Clean up some of the old code for deploying with kfctl.sh since we no longer
use that.
* Related to kubeflow/kubeflow#3905
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/441)
> Fix auto-deployment from master

- release-infra/kf-releasing/.cache/master/.github/issue_label_bot.yaml
With regards to [issue 440](https://github.com/kubeflow/testing/issues/440) of `kubeflow/testing `, issue bot configs need to be updated to use kind labels.
@jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/452)
> Updating issue bot configs

- images/checkout_repos.sh
* The default was (recently?) changed to clone with a depth of 2.
* However, if we want to compute when a file was last modified as when
continuously building our docker images (kubeflow/kueflow#3829) then we need
more of the history
* Add a flag --depth which allows specifying the history. To clone in full
use --depth=all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/458)
> Add a flag to specify the depth to which to clone repos.

- README.md
- prow_config.yaml
- py/kubeflow/testing/ci/kf_unittests.py
- py/kubeflow/testing/run_e2e_workflow.py
As ksonnet is being deprecated, this PR allows for Python functions to be used to parameterize Argo workflows in E2E tests.
Fixes #423 
Related to https://github.com/kubeflow/testing/pull/431 which was rolled back. This should be fixed as with the following section which is moved to the correct place:
```
if w.job_types and not job_type in w.job_types:
logging.info("Skipping workflow %s because job type %s is not one of "
"%s.", w.name, job_type, w.job_types)
continue
```
/assign @jlewi 
/cc @kkasravi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/451)
> Support Python functions in workflows

- hack/run_e2e_workflow_k8s_job.yaml
- py/kubeflow/testing/e2e_tool.py
- py/kubeflow/testing/run_e2e_workflow.py
* When trying to import the py_func in the E2E tests for kubeflow/kubeflow repository, I ran into problems with the import failing because the module kubeflow.kubeflow could not be found
* The issue is tracked kubeflow/testing#467
* Essentially dynamically  adding the kubeflow/kubeflow/py (i.e. from inside python) didn't work
* Could be an issue with namespace packaging
* I spent hours trying to make dynamically importing the modules work but I couldn't figure it out
* Setting python path before invoking python appears to work. So as a workaround we have run_e2e_workflow.py shell out to e2e_tool which writes the workflow to a file. run_e2e_workflow.py then loads it from the file.
* Create a K8s job to run run_e2e_workflow.py to simulate what happens
under prow
* Related to …
> Fix some issues with run_e2e_workflow.py and pyfunc

- images/Dockerfile
Get the test worker to use kustomize 3.2.0 instead of kustomize 2.0.3
This fixes: https://github.com/kubeflow/testing/issues/465
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/470)
> Upgrade kustomize from 2.0.3 to 3.2.0

- py/kubeflow/testing/argo_build_util.py
- py/kubeflow/testing/cleanup_ci.py
* Parse the SSL certificates so that we get the associated domain.
Use this to expire SSL certificates from pre/postsubmits after a couple
hours while leaving the certificates for the auto deployments around longer.
* Minor fixes to some of the other tools.
Related to #461
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/474)
> Improve cleanup of SSl certificates

- playbook.md
- py/kubeflow/testing/cleanup_ci.py
- test-infra/cleanup-kubeflow-ci-deployment.yaml
Fix bugs with cleanup of deployments and clusters
* Disable cache discovery in cleanup_ci.
* Fix #480
* Add a K8s batch job to make it easy to do one off runs of the cleanup script.
* update the playbook.
* Stop using the delete_deployment script; its very outdated and is causing
problems.
Instead lets just issue a delete for the deployment and if that fails to
properly GC everything we can rely on cleanup_ci.py
* We should really be trying to use kfctl to delete things.
* Split up cleanup_deployments into 2 functions one for clusters and one
for deployments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/481)
> Fix bugs with cleanup of deployments and clusters

- py/kubeflow/testing/ci/kf_unittests.py
- py/kubeflow/testing/cleanup_ci.py
- py/kubeflow/testing/e2e_tool.py
- py/kubeflow/testing/prow_artifacts.py
- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/testing/test_py_lint.py
* Prow spyglass are still using kubernetes-jenkins; if we use kubeflow-ci_temp
the results won't show up in spyglass.
* Also we don't need to set suffix to fakesuffix.
* related to kubeflow/kfctl#58
* Fix a bunch of lint errors
* since junit results from lint weren't being surfaced in prow a bunch of issues crept in over time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/488)
> Fix bucket where artifacts are uploaded to

- README.md
- package-lock.json
- py/kubeflow/testing/argo_build_util.py
- py/kubeflow/testing/ci/kf_unittests.py
- py/kubeflow/testing/conftest.py
- py/kubeflow/testing/prow_artifacts.py
- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/testing/test_py_lint.py
- py/kubeflow/testing/util.py
Support subdirectories for junit files and grouping in test grid by name
* We want to support putting junit files in subdirectories e.g.
junit/junit_workflow1/junit_test1.xml
junit/junit_workflow2/junit_test1.xml
* prow_artifacts.py needs to fetch the junit files from GCS in order to
determine if there were any test failures to properly set the prow job
status
* The code however was making an assumption that all results were in
the artifacts dir and not subdirectories
* run_e2e_workflow.py should set a keyword argument test_target_name
to the name of the workflow (as set in prow_config.yaml) for each of
the python functions creating argo workflows.
* We want to use the junit attribute classname to group tests coming
from the same workflow. To do that we need to know the name of the …
> Support subdirectories for junit files and junit_class_name

- README.md
- package-lock.json
- py/kubeflow/testing/argo_build_util.py
- py/kubeflow/testing/ci/kf_unittests.py
- py/kubeflow/testing/conftest.py
- py/kubeflow/testing/prow_artifacts.py
- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/testing/test_py_lint.py
- py/kubeflow/testing/util.py
This reverts commit 81326be365a6e71d3f89fd0ac0e00e99b1ecba81.
* Relates to #489 - group results in test grid
* Roll forward the orginal change now that kfctl_create_e2e_workflow.py
has been updated to handle the extra argument.
* add a leading / to test names; this should hopefully remove an unnecessary grouping layer when
grouping by hierarchy in test grid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/494)
> Revert "Revert "Support subdirectories for junit files and grouping in test grid by name (#490)" (#493)"

- py/kubeflow/testing/ci/kf_unittests.py
- py/kubeflow/testing/py_lint_test.py
* Other workflows are using test_py_lint and making it a pytest breaks them.
* Create a new version py_lint_test.py for people that want to migrate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/496)
> Revert test_py_lint.py

- images/Dockerfile
upgrade kubectl to v1.14.0 in test-worker, the currect new V1.10.0 is too old so caused the porblem beflow.
```
error: SchemaError(io.k8s.api.certificates.v1beta1.CertificateSigningRequestList): invalid object doesn't have additional properties
```
See more in https://github.com/kubeflow/examples/pull/668 and https://github.com/kubeflow/examples/issues/665
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/500)
> upgrade kubectl to v1.14.0 in test-worker

- py/kubeflow/testing/cleanup_ci.py
- py/kubeflow/testing/create_kf_instance.py
- py/kubeflow/testing/create_unique_kf_instance.py
- py/kubeflow/testing/util.py
- test-infra/auto-deploy/deploy-cron-master.yaml
- test-infra/auto-deploy/deploy-master.yaml
Auto deploy job needs to use the new kfctl syntax; also use unique names
Related to #471
* Don't set name in the spec because we want to infer it form directory.
* Create a new script to deploy with a unique name
* Related to: https://github.com/kubeflow/testing/issues/444
* Update cleanup script to clean up new auto-deployed clusters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/495)
> Auto deploy job needs to use the new kfctl syntax.

- py/kubeflow/testing/cleanup_ci.py
- py/kubeflow/testing/cleanup_ci_test.py
- test-infra/cleanup-kubeflow-ci-deployment.yaml
* The auto deployed clusters are now using unique names rather than being
recycled and we rely on cleanup_ci.py to GC old auto-deployments (#444)
* To support this we need to use variable expiration times.
* Deployments created by tests should expire as soon as the test is done (so 1-2 hours)
* But auto-deployed clusters need to live longer
* There are only refreshed periodically by a cron job (~8 hours) we don't
want to delete the cluster before a new one is deployed because we need
a cluster for the example tests
* We want to leave the clusters up as long as we can to facilitate debugging
by people working on example tests.
Related to #444
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> cleanup_ci needs to use different expiration times for auto deployed and E2E clusters

- codelabs/setup-codelab-project.yaml
- py/kubeflow/testing/bulk_deploy.py
- py/kubeflow/testing/create_unique_kf_instance.py
bulk_deploy support Kubeflow v0.6
* For bulk deployments support deploying a v0.6.2 version of Kubeflow
in addition to v0.7
* For v0.6 kfctl apply won't succeed for an already deployed cluster so
we need to check if the deployment already exists and if it does
not redeploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/523)
> bulk_deploy support v0.6

- py/kubeflow/testing/cleanup_ci.py
- py/kubeflow/testing/cleanup_ci_test.py
Some PVCs in `kubeflow-ci` are not cleaned up by the cron job. This PR fixes the problem by adding more pattern to matches these PVCs.
sample log:
```
{
"textPayload": "INFO|2019-11-08T18:00:39|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|215|
Skipping disk gke-zresubmit-unittest-pvc-e3bf5be4-987b-11e9-8266-42010a8e00e9; it does not match any infra type.\n",
"insertId": "qvi653ke2jrzxfq5b",
"resource": {
"type": "k8s_container",
"labels": {
"location": "us-east1-d",
"project_id": "kubeflow-ci",
"cluster_name": "kubeflow-testing",
"pod_name": "cleanup-ci-kubeflow-ci-1573236000-sfv94",
"container_name": "label-sync",
"namespace_name": "kubeflow-test-infra"
}
},
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Add pattern to match e2e test disk

- codelabs/README.md
- codelabs/delete-codelab-endpoints.yaml
- codelabs/setup-codelab-project.yaml
- codelabs/test-codelab-endpoints.yaml
- py/kubeflow/testing/bulk_deploy.py
- py/kubeflow/testing/create_unique_kf_instance.py
- py/kubeflow/testing/delete_kf_instance.py
- py/kubeflow/testing/util.py
Numerous fixes and improvements to bulk deploying Kubeflow with v06
Fix bug with getting credentials in bulk_deploy
* Need to support obtaining credentials to talk to K8s API servier using
the pods service accounnt by calling load incluster config.
* With v06 deployments we need to handle the case where the DM API might
not be enabled yet and enable it before checking if KF exists.
* Don't use workload identity because with workload identity we are seeing
performance problems when issuing a lot of requests that hit the gke metadata
server
Improve the ability to continue deploying v06 deployments that failed.
* With v06 applications check if the ingress actually exists and if
not we will rerun deploy.
* Delete istio-ingressgateway service if its not fully deployed to try to recover.
* Add …
> [WIP] Fix bug with getting credentials in bulk_deploy.py

- .github/workflows/triage_issues.yaml
Related to kubeflow/community#278
Related to kubeflow/community#306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/531)
> Add a GitHub action to add issues to needs triage kanban board.

- py/kubeflow/testing/util.py
Fixes: #537 
Since the API version is apps/v1, We should use `kubernetes.client.AppsV1Api`, instead of `kubernetes.client.ExtensionsV1beta1Api`
https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/stable/nvidia-driver-installer/cos/daemonset-preloaded.yaml
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/538)
> update Daemonset API for GPU driver installing

- apps-cd/README.md
- apps-cd/pipelines/README.md
- apps-cd/pipelines/base/README.md
- apps-cd/pipelines/base/kustomization.yaml
- apps-cd/pipelines/base/pipeline.yaml
- apps-cd/pipelines/base/role-binding.yaml
- apps-cd/pipelines/base/service-account.yaml
- apps-cd/pipelines/base/task.yaml
- apps-cd/runs/README.md
- apps-cd/runs/profile_controller_v1795828.yaml
- py/kubeflow/testing/ci/rebuild-manifests.sh
* kubeflow/testing is the central repository where all reusable engprod
code goes. As a result it makes sense for the reusable Tekton definitions
and scripts related to continuous building and updating of Kubeflow
applications to live here
* For now, we will also centralize the definition of pipelines for all
applications in this repository (as opposed to having them live in
the application repositories).
* This should make it easier to manage and automatically update
all applications.
* Per kubeflow/testing#544 redo how we use kustomize and Tekton to
parameterize the pipelines.
* Individual runs of pipelines will rely completely on Tekton parameter
substitution to create a run to build an image for a specific
application at a specific commit.
* The image URL and git commit of source code …
> Move over the KF cd pipelines into kubeflow/testing and refactor

- apps-cd/Dockerfile
- apps-cd/README.md
- apps-cd/applications.yaml
- apps-cd/pipelines/base/deployment.yaml
- apps-cd/pipelines/base/kustomization.yaml
- apps-cd/run_with_auto_restart.py
- apps-cd/skaffold.yaml
- apps-cd/update_launcher.py
- py/kubeflow/testing/cd/update_kf_apps.py
* Run update_kf_apps.py continuously in a K8s deployment so that
Tekton pipelineruns are continuously created as needed.
* The server uses update_launcher.py to update a clone of kubeflow/testing
before calling update_kf_apps.py. This way it picks up the latest code
and config before running update_kf_apps.py
* Create a skaffold config for running the launcher to create the CD pipelines.
* Useful for debugging and deployment.
Related to #450 continuous updating of Kubeflow applications.
Related to #533 Trigger tekton workflows periodically and in response to GitHub events
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/564)
> Create a Kubernetes deployment to continuously run update_kf_apps for CD

- py/kubeflow/testing/cleanup_ci.py
- py/kubeflow/testing/cleanup_ci_test.py
* We are not properly GC'ing policy bindings for deleted service accounts.
* The problem is that we only consider service accounts matching a certain
regex and that regex isn't matching service accounts for our auto-deployed
clusters.
* Using a regex should be unnecessary. If a service account doesn't exist
that should be a sufficient criterion that the policy bindings should be
deleted.
Related to: kubeflow/testing#543
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/566)
> Fix cleanup logic for IAM policy bindings

- apps-cd/applications.yaml
* Context should be the components directory see
Related to kubeflow/kubeflow#4582
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/567)
> Fix context for notebook-controller.

- py/kubeflow/testing/cleanup_ci.py
- py/kubeflow/testing/cleanup_ci_test.py
This reverts commit 4ebe57134446afe6aa5bbd33494d91831035a30f.
The list of service accounts only includes service accounts owned by the
project. So we ended up deleting bindings for service accounts owned by
other projects such as the service accounts.
related to: #566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/568)
> Revert "Fix cleanup logic for IAM policy bindings (#566)"

- py/kubeflow/testing/python-license-tools/README.md
- py/kubeflow/testing/python-license-tools/pipfile_to_github_repo.py
Fixes #539, as Python is the last language Kubeflow application uses that don't have a way to extract licenses of dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/569)
> Add tool and guide for getting python license information

- py/kubeflow/testing/cleanup_ci.py
- py/kubeflow/testing/cleanup_ci_test.py
- py/kubeflow/testing/test_data/trim_bindings.input.yaml
- py/kubeflow/tests/cleanup_ci_test.py
- test-infra/cleanup-kubeflow-ci-deployment.yaml
* We want to cleanup bindings for service accounts that don't exist
as a way to GC any bindings that might otherwise accumulate.
* However, we only want to GC bindings for service accounts that are
owned by that project because only those service accounts will be listed
as service accounts for that project
e.g. in the project kubeflow-ci-deployment; we should only delete bindings
for the service accounts
${NAME}@kubeflow-ci-deployment.iam.gserviceaccount.com
Any other bindings should be preserved.
* related to: #566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/570)
> Fix cleanup logic for IAM policy bindings.

- py/kubeflow/testing/cleanup_ci.py
- py/kubeflow/testing/cleanup_ci_test.py
- py/kubeflow/testing/create_unique_kf_instance.py
- py/kubeflow/testing/test_data/cleanup_deployments.yaml
* For each KF version (master, v1.0, etc...) we only want to keep
the most recent N deployments (N=3 right now). Otherwise we end up
running out of quota in the deployments project.
* Fix kubeflow/testing#584 out of quota errors due too many auto deployed
clusters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/586)
> Only keep the 3 most recent auto deployments for each version.

- apps-cd/applications.yaml
- apps-cd/pipelines/base/config/app-pipeline.template.yaml
- apps-cd/pipelines/base/pipeline.yaml
- apps-cd/pipelines/base/task.yaml
- apps-cd/pipelines/overlays/dev/deployment.yaml
- py/kubeflow/testing/cd/test_data/notebook_controller.expected.yaml
- py/kubeflow/testing/cd/update_kf_apps.py
- py/kubeflow/testing/cd/update_kf_apps_test.py
- py/kubeflow/testing/kf_logging.py
* Update the Tekton pipelines to support applications whose source
code isn't in the kubeflow repository (e.g. TFJob controller and pytorch)
* We need to generalize the name of the git resource containing
the application to be app-repo.
* update_kf_apps.py needs to filter out repositories that aren't need for
a particular application; attaching extra resources to a pipeline causes
the run to fail.
* Update tests to work with assumption that source could be a different
repository.
* Use structured logging to make it easier to find logs about a particular
application
Related to #450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/587)
> Add TFJob and PyTorch controller to the list of applications for CD.

- py/kubeflow/testing/tools/applications.py
* This is a replacement for
https://github.com/kubeflow/manifests/blob/master/hack/update-instance-labels.sh
* We don't want to assume all applications are at the same version
* This script makes it easier to set a different version for a specific
application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/596)
> Create a script to make updating application resources easier.

- py/kubeflow/testing/get_kf_testing_cluster.py
seems like the new convention is `kf-master` instead of `kf-vmaster`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/597)
> update default pattern to match new convention

- py/kubeflow/testing/tools/applications.py
* If we don't coerce versions to strings version like "0.2" will be
dumped as floats to YAMLs. This will cause problems because kubernetes
requires values to be string -> string
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/599)
> Coerce versions to strings

- images/Dockerfile
- images/Dockerfile.py3
- images/manifest/README.md
- images/manifest/kustomization.yaml
- images/manifest/statefulset.yaml
- images/skaffold.yaml
* Related to kubeflow/testing#560 - python3 lint
* We need this because we need a newer (3.8) version of pylint
to allow for python3.8 syntax like f strings.
* In this pass we eschewed the following packages which I don't think we
need anymore
* ksonnet
* helm
* glide (should be using go modules and staged builds)
* docker
* nodejs (should be using staged builds)
* Create a skaffold config to build the image.
* Related to: kubeflow/kfctl#228 endpoint test is failing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/606)
> Create a python3.8 version of the worker image

- py/kubeflow/testing/cleanup_ci.py
* Fix #611 - out of SSL certificate quota because auto-deployed certificates
not GC'd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/612)
> * Update cleanup_ci to match regexes for new autodeployed clusters

- label_sync/README.md
- label_sync/acm_repo/README.md
- label_sync/acm_repo/namespaces/batch_v1beta1_cronjob_label-sync-cron.yaml
- label_sync/acm_repo/namespaces/github-admin/github-admin.yaml
- label_sync/acm_repo/namespaces/~g_v1_configmap_label-sync-v2-89b54b7724.yaml
- label_sync/acm_repo/system/README.md
- label_sync/acm_repo/system/repo.yaml
- label_sync/cluster/label_sync_cron_job.yaml
- label_sync/hydrate.sh
- label_sync/kubeflow_label.yml
- label_sync/kustomization.yaml
- label_sync/label_sync_acm_config.yaml
* Define a kustomize package to generate the config map from the labels
* ACM requires the directory structure follow a certain format so we
created the directory label_sync/acm_repo
* A simple shell script runs kustomize to dump the manifests to the directory.
Related to #624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/625)
> Use Anthos Config Management to continually sync the label config to the cluster

- py/kubeflow/testing/go-license-tools/README.md
- py/kubeflow/testing/go-license-tools/get_github_license_info.py
- py/kubeflow/testing/python-license-tools/README.md
Simple change with two purpose:
* verify the Prow _presubmit_ is functional for this repo.
* update grammar in string literals:  Git~h~Hub (once merged will verify _postsubmit_)
> Fix casing for GitHub references

- README.md
fix #627
I also updated the string reference of ~gubernator~ to [**spyglass**](https://github.com/kubernetes/test-infra/tree/master/prow/spyglass#spyglass) which is the current artifact viewer in Prow.
> Update README to reflect Kubeflow migration to prow build cluster

- images/Dockerfile.py3
* Go builds of started to break and this appears to be due to the use of
1.12.
* See kubeflow/manifests#1104
* See kubeflow/kfctl#306
* New image is gcr.io/kubeflow-ci/test-worker-py3:e9afed1-dirty
> Upgrade to go 1.14 (from 1.12) in the test worker image.

- test-infra/auto-deploy/manifest/config/deployments.yaml
* Related to kubeflow/manifests#1063
* Sets up an autodeployment which uses the v3 version of the kustomize manifests
so we can begin testing that.
> Add an auto-deploy entry which uses the KFDef stacks.

- py/kubeflow/testing/util.py
Partial revert of commit afd9f952c4d34affbd2a6ec36849486c4dbbe556.
The change in the self-signed logic breaks presubmits with the following error
E           kubernetes.client.rest.ApiException: (409)
E           Reason: Conflict
E           HTTP response headers: HTTPHeaderDict({'Audit-Id': '85305103-054e-4795-a45e-f802de1ae4ea', 'Content-Type': 'application/json', 'Date': 'Wed, 15 Apr 2020 00:31:03 GMT', 'Content-Length': '352'})
E           HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on ingresses.extensions \"envoy-ingress\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"envoy-ingress","group":"extensions","kind":"ingr …
> Revert "Don't use self signed certificates in auto-deployed KF instances (#637)"

- playbook/playbook.md
- py/kubeflow/testing/cleanup_ci.py
* If we don't cleanup unmanaged certificates we will run out of ceritifacte
quota (#636).
* For unmanaged certificates we set a large expiration time (7 days).
The only source for unmanaged certificates should be some tests
which are still using self-signed certificates as a work around for lets
encrypt quota issues. We should be able to stop using self signed certificates
becaue managed certificates should no longer have those limits
Fix #636
> Cleanup script should cleanup unmanaged certificates.

- playbook/auto_deploy.md
- py/kubeflow/testing/create_unique_kf_instance.py
- test-infra/auto-deploy/manifest/config/deploy-kubeflow.yaml
* Add support to create_kf_unique_instance.py to use an untarred version of kfctl
* This is needed to deploy the new V3 manifests using stacks: kubeflow/manifests#1063
> Improve auto deploy infrastructure

- py/kubeflow/testing/cleanup_ci.py
* There is a bug in the SSL certificate cleanup code which is preventing
certificates from being GC'd.
* Fix #636
> Fix cleanup certificates.

- py/kubeflow/testing/create_kf_from_gcp_blueprint.py
- py/kubeflow/testing/create_kf_instance.py
- test-infra/management/instance/cnrm-install-kubeflow-ci-deployment/per-namespace-components.yaml
- test-infra/management/instance/cnrm-install-kubeflow-ci-deployment/service_account.yaml
* Create a simple script to deploy Kubeflow using the GCP blueprint.
This is basically just a wrapper around make commands.
* This is the first step in setting up auto deployments of the GCP
blueprint for CI purposes.
*  kubeflow/gcp-blueprints#5
* Fix some bugs in the management cluster that popped up while testing
the blueprint
* Fix CNRM install for the kubeflow-ci-deployment namespace.
CNRM wasn't properly configured to administer that namespace.
The appropriate role bindings weren't being created in the correct
namespaces and the statefulset was using the host project and not the
managed project.
* See #644 for reference on the management cluster settup
* We should use the kubeflow-testing@kubeflow-ci service account
and not a service account owned by project kubeflow-ci-deployment …
> A simple python script to deploy Kubeflow using the GCP blueprint.

- acm-repo/namespaces/auto-deploy/batch_v1beta1_cronjob_cleanup-ci-kubeflow-ci-deployment.yaml
- acm-repo/namespaces/auto-deploy/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
- acm-repo/namespaces/auto-deploy/~g_v1_configmap_cleanup-config-4bm54d2bmb.yaml
- playbook/README.md
- py/kubeflow/testing/cleanup_blueprints.py
- py/kubeflow/testing/cleanup_ci.py
- py/kubeflow/testing/cnrm_clients.py
- py/kubeflow/testing/create_context.py
- tekton/templates/Makefile
- tekton/templates/tasks/cleanup-kubeflow-ci.yaml
- tekton/templates/tasks/kustomization.yaml
- test-infra/README.md
- test-infra/cleanup/Makefile
- test-infra/cleanup/README.md
- test-infra/cleanup/cleanup-blueprints-pipeline.yaml
- test-infra/cleanup/cleanup-ci-cronjob.yaml
- test-infra/cleanup/kustomization.yaml
* We want to auto-deploy the GCP blueprint (kubeflow/gcp-blueprints#5)
* We need to add logic and K8s resources to cleanup the blueprints so
we don't run out of GCP quota.
* Create cleanup_blueprints.py to cleanup auto_deployed blueprints.
* Don't put this code in cleanup_ci.py because we want to be able to
use fire and possibly python3 (not sure code in cleanup_ci is python3
compatible)
* Create a CLI create_context.py to create K8s config contexts. This will
be used to get credentials to talk to the cleanup cluster when running
on K8s.
* Create a Tekton task to run the cleanup script. This is intended
as a replacement for our existing K8s job (#654). There's a couple reasons
to start using Tekton
i) We are already using Tekton as part of AutoDeploy infrastructure.
ii) We can leverage …
> Code and jobs to cleanup the the new auto-deployed blueprints.

- py/kubeflow/testing/auto_deploy/reconciler.py
- py/kubeflow/testing/delete_kf_instance.py
* The reconciler is running amok because in #657 we changed the code
to skip over deployments with no manifest field because we couldn't get
the zone. It turns out the lack of the manifest is an indication that
the deployment failed. By not matching these deployments we end
up retrying the auto-deployment. This is causing a cascading failure
because we end up using up all our DM quota which in turn causes auto
deployments to fail which in turn causes us to try again and eat up
more deployments.
* This PR fixes that by matching deployments even if the manifest field
is missing. This should prevent us from repeatedly retrying.
* Add exponential backoff to delete deployments. Because of the above
error we are bumping to write quota limits per day which is impacting
our ability to GC …
> Fix auto-deployments reconciler.

- README.md
- playbook/playbook.md
Seems we need to put --project at the beginning to make the command work
```
gcloud container clusters get-credentials kubeflow-testing --zone us-east1-d --project kubelow-ci
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=Project lookup error: permission denied on resource 'projects/kubelow-ci' (or it may not exist).
gcloud --project=kubeflow-ci container clusters get-credentials kubeflow-testing --zone us-east1-d
Fetching cluster endpoint and auth data.
kubeconfig entry generated for kubeflow-testing.
```
Just in case someone experience same issue
> Fix cluster get-credentials  command in playbook

- py/kubeflow/testing/cleanup_ci.py
* Remove references to blueprints; this should not have been committed.
We use a separate script to cleanup blueprints.
Related to #660
> Fix cleanup_ci.py; remove references to blueprints.

- py/kubeflow/testing/cleanup_ci.py
- py/kubeflow/testing/cleanup_ci_test.py
- py/kubeflow/testing/gcp_util.py
* To cleanup orphaned backend services associated with K8s ingresses
we need to match the backend service to a URL map. If the URL map
doesn't exist then its orphaned and we can delete it.
* Similarly for instance groups associated with K8s ingresses
we need to map them to URL maps and delete them if the URL
map doesn't exist.
Related to 
kubeflow/testing#660
kubeflow/testing#664
> Cleanup orphaned backend services and instance groups.

- py/kubeflow/testing/create_kf_from_gcp_blueprint.py
* GCP blueprint autodeployments is failing because of the unavailability
of the cert-manager webhook. This should fix the issue by adding retries.
Related to kubeflow/gcp-blueprints#43
> Add retries to GCP blueprint deployment for webhook.cert-manager.io errors

- apps-cd/README.md
- apps-cd/latest_image.json
- apps-cd/pipelines/base/config/app-pipeline.template.yaml
- apps-cd/pipelines/base/kustomization.yaml
- apps-cd/requirements.txt
- py/kubeflow/testing/cd/update_kf_apps.py
Fix apps CD; install jinja2 library
* The scripts to generate the tests now depend on the jinja2 library but
its not in the container.
* Add some docs for debugging.
* Related to kubeflow/testing#631
* Catch FilenotFoundErrors
* The problem is that on master the location of some of the kustomize
manifests changes (e.g. v3 versions) but for the v1.0 branches
these paths won't exist. So we should just catch these errors
and continue.
* Update the docker image used by the Tekton pipeline because we need jinja2.
* Example PR where tests passed: kubeflow/manifests#1273
> Fix apps CD; install jinja2 library

- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_gcp-kf-ready.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_golang-test.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_gcp-kf-ready.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_golang-test.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
- images/Dockerfile.py3
- images/README.md
- images/latest_images.json
- tekton/templates/pipelines/gcp-kf-ready.yaml
- tekton/templates/pipelines/kustomization.yaml
- tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
- tekton/templates/tasks/go-tests.yaml
- tekton/templates/tasks/kf-ready-task.yaml
- tekton/templates/tasks/kustomization.yaml
* Related to kubeflow/gcp-deployments#51; to test KF deployments are
ready we want to create a Tekton pipeline to run the tests
to verify if KF is ready.
* Add some dependencies to the test worker image
* Install dateutil
* install pytest-timeout in the worker image so we can set the --timeout
* Add a Tekton task to check if KF is ready.
* This runs our existing test to verify that various KF applications
are ready.
* Tasks should use the version of the kubeflow/testing/py cached in the docker image rather than checking out the testing repo.
* Related to kubeflow/gcp-deployments#52 run a test to check that
KF applications are deployed.
> Create a task and pipeline to check IAP endpoint and KF app deployements

- apps-cd/README.md
- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/testing/tekton_client.py
* Periodic runs aren't associated with a repository/commit; so we shouldn't
try to substitute into the pipelineruns.
* Add exception handling so we keep going if a workflow has an exception.
* Fix: #696
> Fix periodic runs of tekton workflows.

- py/kubeflow/testing/create_kf_from_gcp_blueprint.py
Part of https://github.com/kubeflow/gcp-blueprints/issues/61
Some values in upstream/manifests/stacks/gcp contain kpt setters to support default workload identity bindings
> let kpt set value in upstream/manifests/stacks/gcp

- py/kubeflow/testing/create_kf_from_gcp_blueprint.py
/assign @jlewi 
Fixes https://github.com/kubeflow/gcp-blueprints/issues/59
Before we make gcp blueprint completely compliant to regional clusters, let's use regional clusters first to pass testing.
> Use zonal cluster for gcp blueprint

- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
- py/kubeflow/testing/get_kf_testing_cluster.py
- py/kubeflow/tests/get_kf_testing_cluster_test.py
- tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
* Modify get_kf_testing_cluster.py so we can output to a YAML file
information about the cluster that we matched against.
* This is necessary to allow getting information such as the name of
the deployment in subsequent steps/tasks.
* Refactor get_kf_testing_cluster.py so we can start using the python Fire
module to create CLI entrypoints as opposed to using argparse.
* Provide backwards compatibility with argpase
Related to: kubeflow/gcp-blueprints#60 endpoint ready test is failing
> GCP endpoint ready test needs to set the name of the cluster

- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
- docs/tekton.md
- tekton/templates/tasks/notebook-test-task.yaml
* Python path should be /srcCache not /src
* Related to kubeflow/gcp-blueprints#65
> Fix copy-artifacts step in mnist notebook tests.

- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
- tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
- tekton/templates/tasks/kf-ready-task.yaml
- tekton/templates/tasks/notebook-test-task.yaml
* Related kubeflow/gcp-blueprints#51 get-credentials isn't finding any clusters
because when using Fire the parameter should be --pattern not --location
* Related kubeflow/gcp-blueprints#65 When copying the bucket output
in the notebook tests the parameter should be params.notebook-output
not params.output
> Fix bugs in GCP blueprint tests

- acm-repos/kf-ci-v1/namespaces/auto-deploy/apps_v1_statefulset_test-pod.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/~g_v1_service_test-pod.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/apps_v1_statefulset_test-pod.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/~g_v1_service_test-pod.yaml
- tekton/templates/pipelines/kustomization.yaml
- tekton/templates/pipelines/test-pod.yaml
- tekton/templates/tasks/notebook-test-task.yaml
Fix get-credentials in notebook tasks
* Related to kubeflow/gcp-blueprints#65
> Fix get-credentials; To support debugging of the test worker image deploy a stateful set that is in sync with the worker image

- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
- tekton/templates/pipelines/notebook-test-pipeline.yaml
* We need to upload the junits to the artifacts/junit_* directory
Related to kubeflow/gcp-blueprints#65
> Directory for junit file for notebooks is incorrect

- go/Dockerfile.prctl
- go/cmd/prctl/main.go
- go/cmd/prctl/main_test.go
- go/go.mod
- go/prctl_latest_image.json
* Fix the docker image; I switched the base image to alpine but
didn't update the pkg commands from apt to apk.
* Refactor the code to make it easier to write a unittest for the error
regexes.
* Use a global map for the regexes
* Use named constants for the particular error types
* We should be using CombinedOutput in order to get stdout and stderr
when shelling out.
* Mark required flags
* Use working directory as default directory
* Change flag name for push to refspec
* Add an option to format logs as json
* This is needed when running in cluster and using stackdriver so
that multi line entries and metadata fields like level and filename
are recorded as structured entries.
* Add kustomize to the prctl image
* This is a quick fix so we can use the prctl image to run hydration
of …
> Bug fixes and improvements to prctl

- py/kubeflow/testing/run_e2e_workflow.py
Since python 2.7 is used `FileNotFoundError` is not available. I dont know if the best way it so overwritt it for python2 or replace it with IOError? 
Error message currently: 
```bash
INFO|2020-07-04T12:06:42|/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py|187| Job is type presubmit; looking for url https://github.com/kubeflow/mpi-operator.git
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 621, in <module>
final_result = main()
File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 611, in main
return …
```
> Bug: NameError: global name 'FileNotFoundError' is not defined

- go/cmd/prctl/main.go
- go/pkg/ghrepo/repo.go
- go/pkg/ghrepo/repo_test.go
- go/prctl_latest_image.json
* In tekton tasks we can get the URL of the repo directly from
the git resource so being able to parse OWNER/REPO from a URL
avoids having to expose an additional parameter.
> prctl should support using urls for the flag --repo

- py/kubeflow/testing/util.py
Tests should be using the V1 API for deployments.
related to: kubeflow/gcp-blueprints#67
> Update tests to work with Kubernetes 1.16

- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
- tekton/templates/tasks/notebook-test-task.yaml
* The script to run a notebook is missing a trailing slash to indicate
a continued command.
* Related to kubeflow/gcp-blueprints#78
> Fix bug in notebook task

- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
- tekton/templates/tasks/kf-ready-task.yaml
* Related to kubeflow/gcp-blueprints#82 ; The workload identity tests
are failing because we need to know the name of the Kubeflow application
in order to know what service accounts to check.
> Fix workload identity tests by passing in app name.

- Makefile
- acm-repos/kf-ci-v1/namespaces/auto-deploy/apps_v1_statefulset_test-pod.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_golang-test.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/apps_v1_statefulset_test-pod.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_golang-test.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
- docs/tekton.md
- images/Dockerfile.py3
- images/latest_image.json
- tekton/templates/installs/kf-ci-dev/kustomization.yaml
- tekton/templates/installs/kf-ci-dev/service-account-kf-ci.yaml
- tekton/templates/pipelines/test-pod.yaml
- tekton/templates/tasks/cleanup-kubeflow-ci.yaml
- tekton/templates/tasks/deploy-gcp-blueprint.yaml
- tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
- tekton/templates/tasks/go-tests.yaml
- tekton/templates/tasks/kf-ready-task.yaml
- tekton/templates/tasks/notebook-test-task.yaml
* This namespace is intended to allow for testing of changes to the pipelines
without having to first check in the changes.
Revert "Update Dockerfile.py3 (#729)"
This commit doesn't build.
This reverts commit 0de57331b32bfd7defe3a0b30fc5b8bf9abd4adf.
* Fix the entrypoint in Dockerfile.py3 for kubeflow/testing#684
* Rebuild the test worker image
> Setup a kf-ci-dev namespace for manual sync'ing of Tekton pipelines.

- py/kubeflow/testing/create_kf_from_gcp_blueprint.py
* Now that we are using kptfiles; kpt will complain if we try to
set a setter which doesn't exist.
related to kubeflow/gcp-blueprints#89
> Update deploy script to work with Kptfile refactor.

- label_sync/kubeflow_label.yml
Part of https://github.com/kubeflow/pipelines/issues/1653
Googlebot needs "cla: yes" and "cla: no" labels in a repo before it can add/delete these labels.
We can then configure PR protection rule that targets "cla: yes" label.
> chore: add cla yes and no labels for googlebot

- README.md
The link of `https://github.com/kubernetes/test-infra/blob/master/prow/getting_started.md` doesn't exist for sure, and replace it with `https://github.com/kubernetes/test-infra/tree/master/prow#getting-started`
> Fix bad link of Playbook

- images/Dockerfile.py3
- images/Dockerfile.py3.aws
resolve #760 
1. Delete `python3-pip` and python3.6 won't be installed
2. Link pip3/pip to python3.8
3. Link python3 to python3.8
> Fix python3.8 and pip linking

- images/OWNERS
- py/kubeflow/testing/OWNERS
Add OWNERS for shared assets, this should unblock us from development on kubeflow/testing
> Add OWNERS files for Shared Assets

- py/kubeflow/testing/run_e2e_workflow.py
- py/kubeflow/testing/util.py
When developing more test cases, we found it's useful to add `wait_for_ingress ` function to check if K8s Ingress Object is ready.
> Add support to check if ingress is ready

- py/kubeflow/testing/util.py
We should mark test succeed when found ingress.
```
len(ingress.status.load_balancer.ingress[0].hostname) != 0
```
/cc @Jeffwan
> Fix ingress check issue

- test-infra/auto-deploy/manifest/config/pipeline-run-deploy-blueprint-v1.1.yaml
Part of https://github.com/kubeflow/gcp-blueprints/issues/150
> test: pin gcp blueprint auto deploy to v1.1 branch in testing repo

- apps-cd/applications.yaml
I think this is the configuration for CD. I cut v1.2-branch in following repos. Once it's added, they should build images with v1.2 tag and update kubeflow/manifest repo. It also helps on cherry-picks against v1.2-branch. 
/cc @PatrickXYS @jlewi @Bobgy @pingsutw
> Create v1.2.0 config

- py/kubeflow/testing/util.py
Found previous daemonset succeed condition is not sufficient, use 
```
damon.status.desired_number_scheduled == damon.status.current_number_scheduled
```
> Change daemonset succeed condition

- acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-emojichat-wi.yaml
* Needed in order to download models from GCS.
> Add a workload identity binding for the emojichat namespace

- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_py-unittests.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_py-lint.yaml
- acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_py-test.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_py-unittests.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_py-lint.yaml
- acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_py-test.yaml
- tekton/runs/py-test-run.yaml
- tekton/templates/pipelines/py-unittests-pipeline.yaml
- tekton/templates/tasks/py-lint.yaml
- tekton/templates/tasks/py-test.yaml
What?
- add source path for lint and unit test.
- Update to py docker image.
- Fix python path for all the steps.
Usage:
- path for the lint and unit test directory is to be set at the pipelinerun based on the locations in any repository.
For eg. in case of kubeflow/testing repo:
```
- name: lint-src-dir
value: "py"
- name: test-src-dir
value: "py/kubeflow/tests"
``` 
- .pylintrc file should be present at the toplevel of any repository using it.
Ref: https://github.com/kubeflow/testing/issues/769
> Update py unittest

- acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-emojichat-wi.yaml
* We should be using the issue-label-bot-user GCP SA as that's the cluster where
its running.
> Fix the service account for emoji chat

- acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iamserviceaccount_issue-label-bot-user.yaml
* Currently its not defined in CNRM so the IAMPolicyMember rule for WI
is failing.
> Define the issue-label-bot GCP SA in CNRM.

- aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
- aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Resolves https://github.com/kubeflow/internal-acls/issues/354
This is the experiment of using organization webhook to manage webhook configuration on repo-level.
**Checklist:**
1. `cd aws`
> Test for organization webhook

- aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
- aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Resolves #
Revert PR #843 after confirmed that Organization Webhook works for receiving events from all the repos.
**Checklist:**
1. `cd aws`
> Rever PR #843

- Makefile
- acm-repos/kf-ci-v1/namespaces/test-pods/namespace.yaml
- acm-repos/kf-ci-v1/namespaces/test-pods/v1_serviceaccount_default.yaml
- test-infra/kf-ci-v1/gcp_config/Makefile
- test-infra/kf-ci-v1/gcp_config/cluster.jinja
- test-infra/kf-ci-v1/test-pods/kustomization.yaml
- test-infra/kf-ci-v1/test-pods/namespace.yaml
- test-infra/kf-ci-v1/test-pods/service-account.yaml
Part of https://github.com/kubernetes/test-infra/issues/14343
**Checklist:**
1. `cd aws`
> test(gcp): set up GSA workload identity for test pods in kf-ci-v1 cluster

- aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
- aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Resolves https://github.com/kubeflow/internal-acls/issues/354
Use repo-level trigger plugins to avoid aws-kf-ci-bot screaming in other repos.
**Checklist:**
1. `cd aws`
> Use repo-level trigger plugins

- aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/tf-operator-repo.yaml
- aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
- aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/tf-operator-repo.yaml
- aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
Resolves #
[tf-operator#1193](https://github.com/kubeflow/tf-operator/issues/1193)
Move tf-operator presubmit jobs to AWS CI
**Checklist:**
<br> If PR related to **Optional-Test-Infra**,
1. `cd aws`
> Add tf operator presubmit to share test infra config

- OWNERS
Resolves #
Adding myself into OWNERS can avoid the bahavior:
I created a new folder in root directory, got lgtm from others, but can't approve myself to move fast and I don't want to manually merge every time. Since kubeflow/testing active contributors are of 2-3, this PR can help improve efficiency.
**Checklist:**
1. `cd aws`
> Add myself into OWNERS

- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Part of https://github.com/kubeflow/testing/issues/861
Start from migrating pytorch-operator first
**Checklist:**
1. `cd aws`
> Migrate Pytorch-operator

- aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
- aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
- aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
- aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Part of https://github.com/kubeflow/testing/issues/861
Start from migrating pytorch-operator first
**Checklist:**
1. `cd aws`
> Disable pytorch in old test-infra

- aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
- aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Helps #861 
Migrate xgboost-operator to new test-infra
**Checklist:**
1. `cd aws`
> Migrate xgboost-operator repo

- aws/Access/README.md
- aws/Access/assume-role-access/infra-editor/trust-policy.json
- aws/GitOps/clusters/optional-test-infra-daily-worker/namespaces/prow/config.yaml
- aws/Makefile
- aws/README.md
- aws/User/clusters/optional-test-infra-daily-worker/namespaces/prow/configmap/config.yaml
Helps #848 
1. Create one EKS cluster (optional-test-infra-daily-worker), installed with Prow, only use for Periodic Job
2. Experiment with AWS role related to test-infra access, will set up periodic job to sync between upstream to AWS IAM
**Checklist:**
1. `cd aws`
> Add access related resources

- aws-images/daily-worker/Dockerfile
- aws-images/daily-worker/update-iam-assume-role-policy.sh
- aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
- aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
- aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
- aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Helps #861 
Migrate kubeflow/kfserving repo to new test-infra
**Checklist:**
1. `cd aws`
> Migrate KFServing to new test-infra

- aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/eks-cluster-create.yaml
- aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/eks-cluster-teardown.yaml
- aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/kaniko.yaml
- aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/eks-cluster-create.yaml
- aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/eks-cluster-teardown.yaml
- aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/kaniko.yaml
- aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/secret.yaml
Resolves #
Add three reusable tasks from [tekton hub](https://hub-preview.tekton.dev):
* eks-cluster-create
* eks-cluster-teardown
* kaniko
The kaniko image is modified to fetch a custom built image until the pending PRs awslabs/amazon-ecr-credential-helper#253, GoogleContainerTools/kaniko#1515 and GoogleContainerTools/kaniko#1543 will be merged and released to have ECR-public support in kaniko. More information [here](http://bit.ly/kfserving-testing).
**Checklist:**
1. `cd aws`
> Add tekton tasks for eks-cluster-create/teardown and kaniko

- py/kubeflow/testing/go-license-tools/get_github_repo.py
Resolves #887
* GoDoc HTML pages and URL have changed. The script for Go License extraction needed updating.
> Fix godoc parsing for go license script

- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Resolves #897 
It adds a section in the AWS Prow's config for running presubmit jobs for `kubeflow/kubeflow`
**Checklist:**
1. `cd aws`
I wasn't actually able to run the proposed commands, since I don't have a Prow cluster set up.
/cc @PatrickXYS 
/assign @kimwnasptd
> Add kubeflow/kubeflow to prow's presubmits

- aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/kaniko.yaml
- aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/kaniko.yaml
Update kaniko image to the latest official, `v1.5.0`
This closes a series of dependencies for us to have the official kaniko image with support for ecr-public and checkout from PR:
* awslabs/amazon-ecr-credential-helper#253 to get ecr-public support in credential-helper which is used by kaniko
* GoogleContainerTools/kaniko#1515 to get kaniko built with the new credential-helper
* GoogleContainerTools/kaniko#1543 to get kaniko support fetching a repo from the PR refspec
**Checklist:**
1. `cd aws`
> update kaniko image to the official

- acm-repos/kfp-standalone-1/kfp-all.yaml
- test-infra/kfp/Makefile
- test-infra/kfp/kfp-standalone-1/kustomize/instance/proxy-agent-patch.yaml
changed from staging proxy to production proxy of proxy agent  to see whether it can temporarily fix https://github.com/kubeflow/pipelines/issues/5154.
Will change it back to staging proxy once the issues of staging proxy gets resolved.
Resolves #
changed from staging proxy to production proxy of proxy agent 
**Checklist:**
1. `cd aws`
> changed from staging proxy to production proxy of proxy agent 

- py/kubeflow/testing/util.py
Resolves #
Disable environment variable logging to avoid security issue, has no effect in test-infra.
**Checklist:**
1. `cd aws`
> Remove environment variable logs

- aws/IaC/CDK/test-infra/config/static_config/ECR_Resources.py
Related to: https://github.com/kubeflow/testing/issues/922.
I added list of Katib images to the `ECR_Private_Registry_List`.
We should delete current images in ECR for Katib and this script should re-create them.
We currently use this private ECR: `809251082950.dkr.ecr.us-west-2.amazonaws.com`.
/assign @PatrickXYS @gaocegege @johnugeorge 
**Checklist:**
1. `cd aws`
> Add Katib images to private ECR

- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
- prow_config.yaml
Help #919
Migrate kubeflow/testing to optional-test-infra. 
Let's do it step by step, first migrate to optional-test-infra, then check if functionality works fine.
**Checklist:**
1. `cd aws`
> Migrate kubeflow/testing to optional-test-infra

- acm-repos/kf-ci-management/namespaces/kfp-ci/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_vm-cloud-storage-object-admin.yaml
- test-infra/kfp/kfp-standalone-1/instance/iam.yaml
- test-infra/kfp/kfp-standalone-1/instance/kustomization.yaml
Prepare for permission needed in https://github.com/kubeflow/pipelines/pull/5337
**Checklist:**
1. `cd aws`
> test(gcp): add storage object admin permission to kfp-standalone-1-vm GSA

- acm-repos/kf-ci-management/namespaces/kfp-ci/container.cnrm.cloud.google.com_v1beta1_containernodepool_kfp-standalone-1-nodepool-v2.yaml
- test-infra/kfp/kfp-standalone-1/.krmignore
- test-infra/kfp/kfp-standalone-1/Kptfile
- test-infra/kfp/kfp-standalone-1/configsync/config-management-operator.yaml
- test-infra/kfp/kfp-standalone-1/instance/nodepool-patch.yaml
- test-infra/kfp/kfp-standalone-1/upstream/Kptfile
- test-infra/kfp/kfp-standalone-1/upstream/cluster.yaml
Part of https://github.com/kubeflow/pipelines/pull/5337
Add oauth2 scope to a new nodepool and remove the existing one, because it's an immutable field.
**Checklist:**
1. `cd aws`
> test(gcp): expand kfp-ci oauth2 scope to cloud-platform

- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
We should enable CI test on Katib 0.11 release branch.
/assign @PatrickXYS 
/cc @yanniszark @gaocegege @johnugeorge 
**Checklist:**
1. `cd aws`
> Allow test on Katib release-0.11 branch

- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Resolves #https://github.com/kubeflow/tf-operator/issues/1291
Enable prow test for tf-operator `all-in-one-operator` branch
/assign @PatrickXYS @theofpa 
/cc @zw0610 
**Checklist:**
1. `cd aws`
> Enable tf-operator tests in all-in-one-operator branch

- aws/IaC/CDK/test-infra/config/static_config/ECR_Resources.py
Resolves https://github.com/kubeflow/tf-operator/issues/1326
Add universal training image to private ECR
**Checklist:**
1. `cd aws`
> Add universal training image to private ECR

- aws/IaC/CDK/test-infra/config/static_config/ECR_Resources.py
Related: https://github.com/kubeflow/katib/pull/1613
We will use this image to test Optuna Suggestion on AWS cluster.
Do we need to manually run some scripts to add this image to ECR ?
/assign @PatrickXYS 
/cc @kubeflow/wg-automl-leads @g-votte @c-bata 
**Checklist:**
1. `cd aws`
> Add Optuna Suggestion to Katib ECR List

- aws/Access/assume-role-access/infra-viewer/trust-policy.json
Resolves #
```
aws sts get-caller-identity
{
"Account": "692867976397",
"UserId": "692867976397",
"Arn": "arn:aws:iam::692867976397:root"
}
```
```
aws sts assume-role --role-arn arn:aws:iam::809251082950:role/infra-viewer --role-session-name hehe
An error occurred (AccessDenied) when calling the AssumeRole operation: Roles may not be assumed by root accounts.
```
Seems root account is not allowed to assume roles?  https://stackoverflow.com/a/37334769
**Checklist:**
1. `cd aws`
> Fix AssumeRole error by changing root to user

- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Extends the prow cluster to also run the jobs on the 1.4 branch of kubeflow/kubeflow
1. `cd aws`
/cc @PatrickXYS
> Kubeflow kubeflow 1.4 jobs

- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
related-issue: #1355
Resolves #1355
Enable tf-operator tests for v1.2-branch
**Checklist:**
1. `cd aws`
> Enable tf-operator tests in v1.2-branch

- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
adding testing for new release branch v1.3-branch
Resolves #
**Checklist:**
1. `cd aws`
> Enable training-operator tests in v1.3-branch 

- aws/IaC/CDK/test-infra/config/static_config/ECR_Resources.py
Related: https://github.com/kubeflow/katib/pull/1731
We will use tf-mnist-with-summaries to test tfevent-metrics-collctor on EKS.
/assign @theofpa 
/cc @kubeflow/wg-automl-leads
**Checklist:**
1. `cd aws`
> Add tf-mnist-with-summaries in katib ECR list

- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Related: https://github.com/kubeflow/katib/issues/1774.
This PR allows tests on Katib release-0.13 branch
/assign @capri-xiyue @zijianjoy
/cc @gaocegege @johnugeorge
**Checklist:**
1. `cd aws`
> Allow test on Katib release branches

- aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
- aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Refs https://github.com/kubeflow/manifests/issues/2109 
Updated prow to run the jobs on all release branches. Inspired by https://github.com/kubeflow/testing/pull/978, but since we use `v1.5-branch` naming I think that the regex might not be as specific as for Katib. But it's a start.
/assign @zijianjoy 
**Checklist:**
1. `cd aws`
> Update the testing branches for kubeflow and manifests

- test-infra/kfp/kfp-standalone-1/kustomize/instance/limit-range.yaml
Resolves #
This is because the 1.8.0-rc.0 introduced the memory request for mysql instance: https://github.com/kubeflow/testing/blob/8644d09d122105eb6835fcab7b0ea29f6a84b3a4/test-infra/kfp/kfp-standalone-1/kustomize/upstream/third-party/mysql/base/mysql-deployment.yaml#L40. But there is no default limit, which falls back to the LimitRange file in this PR.
**Checklist:**
1. `cd aws`
> pipelines: Increase default memroy limit for Mysql instance

- acm-repos/kfp-standalone-1/kfp-all.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/mysql-patch.yaml
Resolves #
Based on discussion in https://github.com/kubeflow/testing/pull/980, I am applying memory limit only to mysql.
**Checklist:**
1. `cd aws`
> kfp: Set memory limit only for mysql

- acm-repos/kfp-standalone-1/kfp-all.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/status-deletion.yaml
Resolves #
After running `nomos status`, I got this result:
```
*gke_kfp-ci_us-central1_kfp-standalone-1
--------------------
<root>   https://github.com/kubeflow/testing.git/acm-repos/kfp-standalone-1@master
ERROR    de705d1a
Error:   KNV1045: Configs with "status" specified are not allowed. To fix, either remove the config or remove the "status" field in the config:
source: /repo/root/rev-ad4d250e41daf07bfcf28eee86e0b7bee46a10d2/acm-repos/kfp-standalone-1/kfp-all.yaml
metadata.name: applications.app.k8s.io
group: apiextensions.k8s.io
version:
kind: CustomResourceDefinition
For more information, see https://g.co/cloud/acm-errors#knv1045
```
We should unblock the configsync issue by removing the status …
> KFP: Remove status from kfp-standalone-1 manifest

- images/OWNERS
- py/kubeflow/OWNERS
- py/kubeflow/testing/OWNERS
> chore: rm obsolete OWNERS

- acm-repos/kfp-standalone-1/kfp-all.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/workflow-controller-patch.yaml
Resolves #
workflow-controller pod often gets OOMKilled when there were lots of test runs.
Increase memory limit for workflow-controller from 0.5G to 1G.
**Checklist:**
1. `cd aws`
> kfp: increase memory limit for workflow-controller

- acm-repos/kfp-standalone-1/kfp-all.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/metadata-grpc-deployment-patch.yaml
Resolves #
The pod restarted a lot due to OOMKilled:
```
State:          Running
Started:      Tue, 05 Apr 2022 07:01:02 +0000
Last State:     Terminated
Reason:       OOMKilled
Exit Code:    137
Started:      Tue, 05 Apr 2022 06:56:15 +0000
Finished:     Tue, 05 Apr 2022 07:00:44 +0000
Ready:          True
Restart Count:  14
Limits:
cpu:     1
memory:  512Mi
Requests:
cpu:      500m
memory:   512Mi
Liveness:   tcp-socket :grpc-api delay=3s timeout=2s period=5s #success=1 #failure=3
Readiness:  tcp-socket :grpc-api delay=3s timeout=2s period=5s #success=1 #failure=3
```
**Checklist:**
1. `cd aws`
> kfp: increase memory limit for metadata-grpc-deployment

- test-infra/kfp/README.md
Resolves #
`hydrate-kfp-manifests` is already covered by `kfp-update`, so no need to run that separately again.
https://github.com/kubeflow/testing/blob/5a610d067789d63eb5771884946387702d497e57/test-infra/kfp/Makefile#L54
**Checklist:**
1. `cd aws`
> chore(kfp): update instructions for updating kfp deployment in the test cluster.

- images/aws-scripts/create-eks-cluster.sh
Resolves #
training-operator e2e test fails as cluster setup error: https://github.com/kubeflow/training-operator/pull/1575
**Checklist:**
1. `cd aws`
> update eks kubernetes version to 1.19

- images/Dockerfile.py3.aws
Resolves #
Looks most of kubeflow projects like `training-operator`, `katib` and `kserve` have migrated to go 1.17.3, so make sense to update in e2e testing worker image as well.
With go 1.14 we are getting errors like following:
```
/root/go/pkg/mod/k8s.io/client-go@v0.22.3/plugin/pkg/client/auth/exec/metrics.go:21:2: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)
```
**Checklist:**
1. `cd aws`
> Upgrade go version to 1.17.3

- acm-repos/kfp-standalone-1/kfp-all.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/persistent-agent-deployment-patch.yaml
Reduce persistent agent TTL_SECONDS_AFTER_WORKFLOW_FINISH from 24 hours to 8 hours.
`kubeflow-pipelines-samples-v2` are often flaky and deleting completed pods--usually a lot--seems to reduce the flakiness. We can probably reduce the default TTL to 8 hours as I expect most test debugging should happen within such time window.
> kfp: Reduce persistent agent TTL_SECONDS_AFTER_WORKFLOW_FINISH to 8 hours

- acm-repos/kfp-standalone-1/kfp-all.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
- test-infra/kfp/kfp-standalone-1/kustomize/instance/metadata-writer-patch.yaml
Resolves #
Metadata-writer was in a crash-loop due to OOMKIlled.
```
Name:             metadata-writer-546cc4bbb4-fl2ww
Namespace:        kubeflow
Priority:         0
Service Account:  kubeflow-pipelines-metadata-writer
Node:             gke-kfp-standalone-1-kfp-standalone-1-60baa0a0-bg42/10.128.0.45
Start Time:       Thu, 01 Sep 2022 22:16:32 +0000
Labels:           app=metadata-writer
application-crd-id=kubeflow-pipelines
pod-template-hash=546cc4bbb4
Annotations:      kubectl.kubernetes.io/restartedAt: 2022-07-06T13:40:37-06:00
kubernetes.io/limit-ranger: LimitRanger plugin set: cpu, memory request for container main; cpu, memory limit for container main
Status:           Running
IP:               10.44.33.228
IPs:
IP: …
```
> kfp: Increase memory limits for metadata writer to 1Gi
