py/kubeflow/testing/prow_artifacts.py
py/kubeflow/testing/prow_artifacts_test.py
py/kubeflow/testing/util.py
py/kubeflow/testing/util_test.py

* We are moving some of the common python scripts for testing from kubeflow/kubeflow and tensorflow/k8s into kubeflow/testing to make it easier to reuse them in our tests for multiple repositories.
* Organize the python scripts into a proper python package named kubeflow.testing
* This will be used to switch over tensorflow/k8s to using Argo.
* This is a redo of #2 ; I ended up merging that PR in a bad way.

Common python scripts for E2E testing

---

README.md
py/kubeflow/testing/run_e2e_workflow.py

change testing-argo.kubeflow.io to testing-argo.kubeflow.org

---

images/run_workflows.sh

Change test cluster from mlkube-testing to kubeflow-ci

---

images/Dockerfile

Needed in https://github.com/kubeflow/kubeflow/pull/426

Upgrade ksonnet from 0.8 to 0.9 for testing image

---

images/Dockerfile
images/Makefile

* Replace sha256sum because it doesn't work on OSX
Related to https://github.com/kubeflow/kubeflow/issues/432

Add jsonnet to test-worker

---

dev-kubeflow-org/ks-app/.ksonnet/registries/kubeflow/20bdb46ee436b56fb9e3690d2a383b2afc8989f4.yaml
dev-kubeflow-org/ks-app/app.yaml
dev-kubeflow-org/ks-app/components/params.libsonnet
dev-kubeflow-org/recreate_app.sh

Update the dev deployment to the latest RC.

Update to v0.1.0-rc.4

---

dev-kubeflow-org/README.md

Add dev doc for istio setup

---

images/Dockerfile
images/Pipfile
images/Pipfile.lock

Update Pipfile and lock file to reflect this
/cc @lluunn

Add junit-xml package to test image as this will be used to generate testing xml outputs

---

py/kubeflow/testing/test_jsonnet_formatting.py

Add exclude_dirs flag to test_jsonnet_formatting

---

README.md
py/kubeflow/testing/test-data/successful_workflow.yaml
workflows/components/params.libsonnet

Related https://github.com/kubeflow/testing/issues/90
/cc @gaocegege @lluunn

Move away from mlkube-testing to kubeflow-ci

---

test-infra/app.yaml
test-infra/components/argo.jsonnet
test-infra/components/argo.libsonnet

Used manifests from https://github.com/argoproj/argo/tree/master/install/manifests
No longer requires cluster-admin role
/cc @lluunn

Update test-infra argo component to v2.1.0

---

README.md

Fixed list indentation and a few incorrect/outdated file paths.

Small fixings in readme

---

.gitignore

This directory is needed by ksonnet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/141)

Include vendor dir in future commits

---

py/kubeflow/testing/argo_client.py

Retry on exceptions, except TimeoutError
Addresses https://github.com/kubeflow/testing/issues/147
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/148)

Catch and ignore exceptions in wait_for_workflows

---

py/kubeflow/testing/run_e2e_workflow.py
py/kubeflow/testing/test_helper.py
py/kubeflow/testing/util.py

/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/151)

Use logging.exception to log stacktrace

---

py/kubeflow/testing/test_py_lint.py

/assign @ankushagarwal 
/assign @pdmack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/156)

Exclude all vendor directories from lint tests.

---

images/Dockerfile

Related to kubeflow/kubeflow#727
/assign @everpeace 
/assign @ankushagarwal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/155)

Upgrade to ks 0.11 in our tests.

---

label_sync/kubeflow_label.yml

For #154 
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/160)

add area/inference label

---

dev-kubeflow-org/ks-app/app.yaml
dev-kubeflow-org/ks-app/components/katib.jsonnet
dev-kubeflow-org/ks-app/components/params.libsonnet
dev-kubeflow-org/ks-app/vendor/kubeflow/katib/modeldb.libsonnet
dev-kubeflow-org/ks-app/vendor/kubeflow/katib/parts.yaml
dev-kubeflow-org/ks-app/vendor/kubeflow/katib/prototypes/all.jsonnet
dev-kubeflow-org/ks-app/vendor/kubeflow/katib/suggestion.libsonnet
dev-kubeflow-org/ks-app/vendor/kubeflow/katib/vizier.libsonnet
dev-kubeflow-org/recreate_app.sh

/cc @ankushagarwal 
https://github.com/kubeflow/kubeflow/tree/master/kubeflow/katib
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/159)

Add katib to dev.kubeflow.org

---

label_sync/README.md

/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/161)

add instruction to update label sync

---

py/kubeflow/testing/util.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/165)

Remove helm from cluster setup because we don't use it.

---

images/Dockerfile

/assign @lluunn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/176)

Add uuid-runtime package to worker

---

README.md

/cc @activatedgeek
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/188)

Add doc on how to get logs for failed serving test

---

images/Dockerfile

fixes kubeflow/issues/#1540
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/201)

upgrade ksonnet to 0.12.0 and jsonnet to 0.11.2

---

py/kubeflow/testing/argo_client.py

Fixes #204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/206)

Fix retry logic in in argo_client 

---

images/Dockerfile
images/Makefile

* Need to pin version of pipenv to a newer version to fix the bux.
Fix #233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/236)

Fix build of test worker image.

---

images/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/237)

add lib for e2e test

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/235)

Add instructions for debugging tests where the container status isn't available

---

py/kubeflow/testing/util.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/244)

Upgrade daemonset file to 1.10

---

py/kubeflow/testing/util.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/245)

Change daemonset file to version 1.9

---

py/kubeflow/testing/cleanup_ci.py

Fix #250 
/assign @r2d4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/251)

Cleanup script should cleanup abandoned service accounts.

---

OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/272)

Add richardsliu as OWNER

---

py/kubeflow/testing/create_kf_instance.py

Relates to #95
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/286)

Add retry block to kfctl apply all

---

test-infra/ks_app/components/argo.jsonnet
test-infra/ks_app/components/argo.libsonnet
test-infra/ks_app/components/params.libsonnet

* Related to #284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/290)

Upgrade argo ui image to work around bug with logs not showing up.

---

images/build/image_build.json
py/kubeflow/testing/ks_util.py
py/kubeflow/testing/util.py

* Add a generic wait for condition method for CRDs.
* Fix a bug in setup_ks_app to allow for empty params.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/289)

Test utilities for CRDs.

---

README.md

Related to https://github.com/kubeflow/kubeflow/issues/2364
/cc @kunmingg 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/302)

Add step to setup secret in test infra setup

---

admin-infra/README.md
admin-infra/cluster.jinja
admin-infra/cluster.yaml
label_sync/README.md

* Setup a new GKE cluster running the label_sync_cron job.
* Run this on a separate admin cluster because it requires write
privileges on REPOs.
* Create DM configs for setting up this cluster.
Fix #299
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/306)

Fix label_sync by running on an admin cluster.

---

py/kubeflow/testing/cleanup_ci.py

Fix
https://github.com/kubeflow/kubeflow/issues/2401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/311)

Add cron job to clean outdated disks

---

py/kubeflow/testing/cleanup_ci.py
py/kubeflow/tests/cleanup_ci_test.py
py/kubeflow/tests/test-data/iam_bindings.yaml

1. fix https://github.com/kubeflow/kubeflow/issues/2570
2. delete service account only when all keys expired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/319)

clean up unused bindings in iam

---

test-infra/auto-deploy/Makefile
test-infra/auto-deploy/deploy-cron-master.yaml
test-infra/auto-deploy/deploy-cron-v0-4.yaml
test-infra/auto-deploy/deploy-master.yaml
test-infra/auto-deploy/deployment-workflows.sh
test-infra/auto-deploy/init.sh

* Allow setting the zone to deal stockouts #321 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/320)

Create a batch job to allow manual runs of auto-deploying the latest code

---

project_creation/README.md
project_creation/config.yaml

create projects for https://github.com/kubeflow/kubeflow/issues/2580
- Add command instruction on how to create a project in README.
- Add apis to enable 1-click-deployment
- Add load test service account to access the public URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/325)

Update project creation

---

py/kubeflow/testing/cleanup_ci.py

* Fix #328 - Tests failing due to out of firewall quota errors.
* Add a dryrun flag to cleanup ci.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/330)

Cleanup firewall rules.

---

README.md

* Add a gcloud command.
* Add information for filtering by step labels.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/329)

Improve instructions for getting logs for failed runs.

---

py/kubeflow/testing/util.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/336)

Fix an issue with wait_for_deployment; handle case ready_replicas is None

---

py/kubeflow/testing/run_e2e_workflow.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/339)

Fix for presubmits: append last 4 digits of build number

---

py/kubeflow/testing/util.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/341)

Fix bug in wait for statefulset; handle ready replicas is None.

---

playbook.md
test-infra/ks_app/environments/kubeflow-ci/params.libsonnet

* Add a playbook for dealing with  the NFS volume being full.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/347)

Fix NFS volume mounting; the NFS was recreated but still using the old IP

---

label_sync/kubeflow_label.yml

added the devices label
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/351)

add devices label

---

py/kubeflow/testing/get_kf_testing_cluster.py
py/kubeflow/tests/get_kf_testing_cluster_test.py
py/kubeflow/tests/test-data/README.md
py/kubeflow/tests/test-data/deploymentmanager-v2.json

Fixes #273
Script used to inspect deployed testing clusters and returns information such as deployed time or endpoint service names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/354)

get_kf_testing_cluster

---

README.md
py/kubeflow/testing/run_e2e_workflow.py

**Background**
This addresses the issue in #331.
**Changes**
* Dumped workflow results into YAML strings and uploaded them to GCS.
**Tests**
* N/A.
Fix #331 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/360)

Upload workflow status as Prow artifacts

---

images/Dockerfile

kubeflow/metadata use `bazel` to build & test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/369)

Add bazel installation to ci-work image

---

images/Dockerfile

/assign @jlewi @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/371)

upgrade test image go version to 1.12

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/376)

Improve the documentation for debugging tests.

---

playbook.md
test-infra/ks_app/environments/kubeflow-ci/params.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/381)

Fixed typos and some clarification on playbook doc

---

py/kubeflow/OWNERS

Adding new approvers for efficiency.
/assign @jlewi @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/384)

Create OWNERS for py/kubeflow

---

OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/387)

add zabbasi to approvers

---

playbook.md
test-infra/ks_app/environments/kubeflow-ci/params.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/383)

Fix the playbook.

---

py/kubeflow/testing/argo_client.py

* See if this fixes the test failures updating the jupyter web app
image kubeflow/kubeflow#3254
related to #306
related to kubeflow/kubeflow#3254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/395)

Retry on 504 GATEWAY_TIMEOUT

---

README.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/394)

improvements to README.md

---

images/checkout.sh
images/checkout_repos.sh

**Background**
This PR address https://github.com/kubeflow/testing/issues/380.
**Changes**
* Uses `git clone --depth=1`.
**Tests**
Not applicable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/402)

Use git shallow clone

---

py/kubeflow/testing/cleanup_ci.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/404)

Add method to clean up HTTP proxies

---

py/kubeflow/testing/create_kf_instance.py
test-infra/auto-deploy/deploy-master.yaml

#406
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/408)

Use Kustomize and Istio for auto deployment

---

py/kubeflow/testing/create_kf_instance.py
test-infra/auto-deploy/deploy-master.yaml

Fixes #406 
#408 works by using "kustomize@1e6b55258c678c6b151ea17a039acf6170706a23".
This PR pings kustomize version on master.
After this PR we can test if kubeflow master + kustomize master can deploy successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/409)

Fix auto deployment

---

py/kubeflow/testing/run_e2e_workflow.py

See kubeflow/testing#3523
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/411)

If get merge-base fails; keep going don't abort

---

.github/stale.yml

Per https://github.com/kubeflow/testing/issues/427 setting up probot.
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/428)

Add config for probot

---

OWNERS
images/gcb_build/image_build.json
playbook.md
test-infra/ks_app/environments/kubeflow-ci/params.libsonnet

Fix #435
Remove @zabbasi from the OWNERs files to remove auto assignment of reviewers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/436)

Recreate the NFS share to fix out of space

---

py/kubeflow/testing/create_kf_instance.py
test-infra/auto-deploy/deploy-cron-master.yaml
test-infra/auto-deploy/deploy-cron-v0-6.yaml
test-infra/auto-deploy/deploy-v0-6.yaml
test-infra/auto-deploy/set_images.sh

* We need to pick up the changes to auto-deploy.sh to take in argument
kfctl_config
* Update the v0-6 code to use the new RC for 0.6.2 config file.
* Create a batch job for deploying from v0-6
Related to kubeflow/kubeflow#3905
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/443)

Update the docker image used for auto deployment.

---

label_sync/kubeflow_label.yml

Related to: #455
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/456)

Define some labels that can be used to indicate estimated effort for an issue

---

py/kubeflow/testing/cleanup_ci.py

* Now that we are using managed certificates every Kubeflow deployment uses
up SSL certificate quota.
* Certificates are not getting cleaned up so we are running out of quota.
* Add code to our kubeflow-ci-deployment script to cleanup certificates more
than 7 days old.
* Related to kubeflow/testing#461 - auto deployments form master not accessible
* Related to kubeflow/kubeflow#4114 - test_endpoint_ready i failing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/462)

Cleanup SSL certificates in kubeflow-ci-deployment.

---

py/kubeflow/testing/util.py

/cc @jlewi @swiftdiaries @kkasravi 
Signed-off-by: Yannis Zarkadas <yanniszark@arrikto.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/477)

fix wait_for_deployment to also check for apps/v1 deployments

---

py/kubeflow/testing/cleanup_ci.py

Fixes #483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/484)

Pass an empty body to getIamPolicy

---

py/kubeflow/testing/cleanup_ci.py

Related to #480.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/485)

Aggressively GC clusters that are in an error state.

---

py/kubeflow/testing/prow_artifacts.py

* See kubeflow/kfctl#58 junit artifacts aren't being uploaded for some of our
tests because the GCS bucket is being set incorrectly.
* It looks like the problem is that our Argo workflows are setting BUILD_ID
and not BUILD_NUMBER
* To avoid breaking workflows that might still be relying on BUILD_NUMBER
we try BUILD_ID and fall back to BUILD_NUMBER
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/487)

Check environment variable BUILD_ID and use that for the prow bucket.

---

test-infra/auto-deploy/deploy-cron-master.yaml
test-infra/auto-deploy/deploy-master.yaml

* Fix #471
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/472)

autodeploy jobs should pull kfdef specs from kubeflow/manifests

---

py/kubeflow/testing/util.py

util function for presubmit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/497)

util check_secret

---

py/kubeflow/testing/run_e2e_workflow.py

Potential fix for https://github.com/kubeflow/kfctl/pull/51
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/503)

Clone additional repos in prow config python paths

---

py/kubeflow/testing/run_e2e_workflow.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/504)

Fix conditions for checking out additional repos

---

py/kubeflow/testing/run_e2e_workflow.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/505)

Fix the destination path for checking out repos

---

py/kubeflow/testing/create_unique_kf_instance.py
test-infra/auto-deploy/deploy-master.yaml

Related to:
kubeflow/testing#444
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/506)

Fix auto-deployment labels to be valid GCP labels.

---

py/kubeflow/testing/util.py
py/kubeflow/tests/util_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/511)

Add a method to build checkout repos dictionary

---

py/kubeflow/testing/util.py

* Will be used by various tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/514)

Add a utility routine to wait for a batch job to finish.

---

buildcop.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/516)

Start a playbook for the buildcop that focuses on keeping tests healthy.

---

py/kubeflow/testing/get_kf_testing_cluster.py
py/kubeflow/tests/get_kf_testing_cluster_test.py

* Auto deployed clusters are no longer recycling names; instead each
auto deployed cluster will have a unique name
* Use regexes to identify the appropriate auto deployed cluster
* Only consider clusters with a minimum age; this is a hack to ensure
clusters are properly setup.
* Related to: kubeflow/testing#444
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/513)

Update get credentials to work with new auto deploy naming schema

---

py/kubeflow/testing/get_kf_testing_cluster.py

* get_credential isn't activating the service account which is preventing
us from obtaining credentials when run under E2E tests
* the get_credential function should just be invoking get_latest_credential
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/519)

get-credential needs to activate service account

---

codelabs/move_kubeflow_projects_into_folder.sh
codelabs/setup_kubeflow_folder.sh

Create scripts to move projects and setup a folder
* Create a onetime script to setup a folder to own the Kubeflow codelab
projects
* Create a script to be used to bulk move the projects into the folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/521)

Codelabs scripts

---

py/kubeflow/testing/create_unique_kf_instance.py
test-infra/auto-deploy/deploy-cron-master.yaml
test-infra/auto-deploy/deploy-master.yaml

* Related to kubeflow/kfctl#7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/522)

Kubeflow autodeploy jobs need to use kubeflow/kfctl

---

py/kubeflow/testing/cleanup_ci.py

Fixes: #528 
Verified this should work locally.;
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/529)

Gc instance groups based on usage

---

py/kubeflow/testing/go-license-tools/README.md
py/kubeflow/testing/go-license-tools/patch_additional_license_info.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/555)

Fix errors in go licensing tool README

---

apps-cd/applications.yaml
py/kubeflow/testing/cd/update_kf_apps.py
py/kubeflow/testing/cd/update_kf_apps_test.py

update_kf_apps.py should create pipelineruns for images that need to be updated.
* Determine whether an image is already up to date by comparing the desired
image to the image listed in the manifest
* If the image needs to be updated submit the PipelineRun to update the
image.
* Related to #450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/561)

update_kf_apps.py should create pipelineruns for images that need to be updated.

---

py/kubeflow/testing/node-license-tools/.gitignore
py/kubeflow/testing/node-license-tools/README.md
py/kubeflow/testing/node-license-tools/_esm_entrypoint.js
py/kubeflow/testing/node-license-tools/commands/getLicenseInfo.js
py/kubeflow/testing/node-license-tools/node_lic.js
py/kubeflow/testing/node-license-tools/package-lock.json
py/kubeflow/testing/node-license-tools/package.json

This PR introduces Node-License-Tools CLI to `kubeflow/testing`. This should be used to scan deps for node-based projects within the Kubeflow ecosystem. Features include:
- Full-featured CLI with cmd-line support
- Installable as a CLI after clone (node_lic.bat or *nix shell script in `$PATH`)
- Readme added to explain installation/run steps
- Single entry point with modular design to add more commands down the line
- Help menu
- Runtime transpiler to allow es6
- Verbose output
- Graceful handling of errors
- Promise chains baked to handle errors at each level
- Runs Cross-Platform
Installation and cli |
--- |
/area front-end
/priority p0
/assign @avdaredevil
/cc @kwasi @zhenghuiwang @jlewi @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

[Node][License] Introduced Node-License CLI

---

py/kubeflow/testing/create_unique_kf_instance.py

This fixes #601 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/602)

Get email only in create_unique_kf_instance

---

images/Dockerfile.py3

Adding additional installations for the test worker to work on tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/615)

Fix py3 test worker

---

py/kubeflow/testing/cleanup_ci.py

* There was a syntax error so we weren't GC'ing deployments
Fix: #616
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/617)

Fix a bug in clenaup_ci preventing GC'ing of deployments.

---

py/kubeflow/testing/auto_deploy/reconciler.py
py/kubeflow/testing/auto_deploy/reconciler_test.py
py/kubeflow/testing/auto_deploy/test_data/completed_job.yaml

* There is a bug in the code to detect completed jobs. For completed
jobs the condition can be of type "Complete". As a result, we aren't
properly detecting when jobs have been completed and rerunning them
if needed.
Related to #762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/619)

Fix autodeploy job

---

label_sync/kubeflow_label.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/testing/623)

Added gsoc label to kubeflow_label.yml

---

images/Dockerfile.py3

* Related to kubeflow/kfctl#306

Add go junit-report to test worker image

---

label_sync/kubeflow_label.yml

https://github.com/kubeflow/kfserving/issues/810

Define kfserving area labels

---

apps-cd/applications.yaml

Apps CD scripts need to be updated to work with kustomize refactor

---

apps-cd/applications.yaml

Forgot to add `sourceRepo` in #673

Add sourceRepo in apps-cd/applications.yaml 

---

apps-cd/applications.yaml

Related to https://github.com/kubeflow/xgboost-operator/issues/89
cc @jlewi @terrytangyuan

Auto update for xgboost image tag in manifests

---

py/kubeflow/testing/tekton_client.py

* The CLI code isn't actually doing anything when invoked with "junit-and-upload". This was a bug introduced by #683
Related to #685

Fix a bug in tekton_client.py

---

apps-cd/applications.yaml

related to https://github.com/kubeflow/testing/issues/631
/cc @jlewi

Create a v1.1.0 config in Apps CD scripts

---

acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_golang-test.yaml
acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_golang-test.yaml
acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
images/latest_image.json
tekton/runs/nb-test-run.yaml
tekton/templates/tasks/cleanup-kubeflow-ci.yaml
tekton/templates/tasks/deploy-gcp-blueprint.yaml
tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
tekton/templates/tasks/go-tests.yaml
tekton/templates/tasks/kf-ready-task.yaml
tekton/templates/tasks/notebook-test-task.yaml

* Related to kubeflow/gcp-blueprints#60 previous image was missing
latest get-credentials code.

Update the worker image in tekton pipelines

---

OWNERS

I’d like to help review the code

Add pingsutw to OWNERS

---

acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
tekton/templates/pipelines/notebook-test-pipeline.yaml

* artifacts-gcs on the image build step needs to match the run-notebook
step

Fix notebook test

---

test-infra/base/pvc.yaml

Recreate the NFS share because we ran out of space.

---

acm-repos/kf-ci-v1/namespaces/auto-deploy/apps_v1_deployment_auto-deploy-server.yaml
acm-repos/kf-ci-v1/namespaces/auto-deploy/~g_v1_configmap_auto-deploy-config-2778d8c6c8.yaml
test-infra/auto-deploy/manifest/config/pipeline-run-deploy-blueprint-v1.1.yaml
test-infra/auto-deploy/manifest/kustomization.yaml

Related to: kubeflow/gcp-blueprints#46
Related to: kubeflow/gcp-blueprints#77

Start auto-deploying the GCP blueprints v1.1 branch

---

OWNERS

Trying to put some time on this repo and help improve test infra. I will help review coming PRs.

Add Jeffwan@ as reviewer

---

label_sync/acm_repo/namespaces/batch_v1beta1_cronjob_label-sync-cron.yaml
label_sync/acm_repo/namespaces/~g_v1_configmap_label-sync-v2-g8d5bm2m78.yaml
label_sync/kubeflow_label.yml

https://github.com/kubeflow/pipelines/issues/4541

chore: add new label area/kfp/aws-sagemaker-components

---

test-infra/management/instance/cnrm-install-system/0-cnrm-system.yaml
test-infra/management/instance/cnrm-install-system/crds.yaml

Related to kubeflow/gcp-blueprints#143

Upgrade CNRM in Kubeflow ci management from 1.9 to 1.27.2

---

py/kubeflow/testing/ci/kf_unittests.py
py/kubeflow/testing/create_kf_from_gcp_blueprint.py

What?
As per the title.
Why?
The process of setting kfp values has been changed due to redundant variables.

Update set values tests

---

py/kubeflow/testing/run_e2e_workflow.py

Resolve #774 
/cc @jlewi @Jeffwan  
This effects all the kubeflow repos which have not yet migrated to Tekton

Revert Code Change

---

test-infra/management/configsync/config-management.yaml

* ACM config should be sync'ing to kubeflow/testing@master

Update management ACM config

---

OWNERS
py/kubeflow/OWNERS

chore: update OWNERS

---

acm-repos/kf-ci-v1/namespaces/auto-deploy/batch_v1beta1_cronjob_cleanup-ci-kubeflow-ci-deployment.yaml
acm-repos/kf-ci-v1/namespaces/auto-deploy/~g_v1_configmap_cleanup-config-4bm54d2bmb.yaml
test-infra/cleanup/Makefile

/assign @jlewi 
I'll merge first to see if it works

test: include cleanup cronjob in acm repos

---

acm-repos/kf-ci-v1/namespaces/auto-deploy/batch_v1beta1_cronjob_cleanup-ci-kubeflow-ci-deployment.yaml
acm-repos/kf-ci-v1/namespaces/auto-deploy/~g_v1_configmap_cleanup-config-dh2846bbg5.yaml
py/kubeflow/testing/cleanup_blueprints.py
test-infra/cleanup/cleanup-blueprints-pipeline.yaml

/cc @jlewi 
Some further fixes, need to merge to try

test(gcp): fix cleanup_blueprints

---

py/kubeflow/testing/cleanup_blueprints.py
py/kubeflow/testing/cnrm_clients.py
py/requirements.txt

Part of https://github.com/kubeflow/testing/issues/793

test(gcp): fix cleanup_blueprints.py one more attempt

---

.gitignore
images/Dockerfile.py3
images/Dockerfile.py3.aws
py/kubeflow/testing/util.py

There are some changes in the PR:
1. Upgrade K8s python client version from 9.0 to 12.0
2. Add function to check daemonset status
3. Add `pytest_cache` directory in `.gitignore`
/cc @Bobgy @jlewi @Jeffwan

Upgrade Python K8s Client SDK version to 12.0.0

---

py/kubeflow/testing/create_kf_from_gcp_blueprint.py

Depended on by https://github.com/kubeflow/gcp-blueprints/pull/169

test(gcp): revert set values commands for kubeflow package

---

notebook_testing/Dockerfile.notebook_runner

Part of https://github.com/kubeflow/gcp-blueprints/issues/174

test: fix notebook_runner dockerfile

---

tekton/templates/tasks/notebook-test-task.yaml

Part of https://github.com/kubeflow/gcp-blueprints/issues/174

test: fix notebook-test task

---

acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/container.cnrm.cloud.google.com_v1beta1_containercluster_kfp-standalone-1.yaml
acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/container.cnrm.cloud.google.com_v1beta1_containernodepool_kfp-standalone-1-nodepool.yaml
acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-logging.yaml
acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-policy-monitoring-viewer.yaml
acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-policy-monitoring.yaml
acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-policy-storage.yaml
acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iamserviceaccount_kfp-standalone-1-vm.yaml
test-infra/kfp/kfp-standalone-1/instance/kustomization.yaml

test(gcp): update kfp-standalone-1 labels

---

Makefile
acm-repos/kf-ci-management/namespaces/kfp-ci/serviceusage.cnrm.cloud.google.com_v1beta1_service_container.googleapis.com.yaml
gcp/packages/cluster-standard/upstream/services/enable-services.yaml
gcp/packages/cluster-standard/upstream/services/kustomization.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/upstream/services/enable-services.yaml
test-infra/kfp/kfp-standalone-1/upstream/services/kustomization.yaml

test(kfp): enable GKE service for kfp-ci project

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/instance/proxy-agent-patch.yaml

test(kfp): use staging proxy instead

---

test-infra/kfp/Makefile
test-infra/kfp/endpoint

test(kfp): update KFP endpoint to staging

---

acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/namespace.yaml
acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/rolebinding-kf-ci-v1-cnrm-admin.yaml

test(gcp): fix kf-ci-v1 permissions on kubeflow-ci-deployment project

---

acm-repos/kf-ci-management/namespaces/kfp-ci/iam.yaml
test-infra/kfp/Makefile
test-infra/kfp/iam/iam.yaml

test(kfp): add ci-team@kubeflow.org as owner for kfp-ci project

---

acm-repos/kf-ci-management/namespaces/kfp-ci/iam.yaml
test-infra/kfp/Makefile
test-infra/kfp/iam/Kptfile
test-infra/kfp/iam/iam.yaml

/cc @capri-xiyue 
Documentation for added resource: https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampolicymember

test(kfp): grant prow sa permission to access kfp-standalone-1

---

aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
aws/Makefile

Fix bad file name introduced from init PR https://github.com/kubeflow/testing/pull/836

Fix bad file name

---

.github/pull_request_template.md
aws/Doc/architecture.md
aws/Doc/onboarding.md
aws/README.md
aws/User/README.md

The change I made in this PR:
1. Add more documentations for optional-test-infra
2. Create a PR template so that other folks can take advantage of it
/cc @theofpa @Bobgy

Add more doc for optional-test-infra and PR template

---

.github/pull_request_template.md

Resolves #
Fix one unnecessary item in PR template
**Checklist:**
1. `cd aws`

Fix one unnecessary item in PR template

---

acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/container.cnrm.cloud.google.com_v1beta1_containercluster_code-intelligence.yaml
acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/container.cnrm.cloud.google.com_v1beta1_containernodepool_code-intelligence-cpu-pool-v1.yaml

chore(gcp): migrate to use e2 machines

---

acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/container.cnrm.cloud.google.com_v1beta1_containercluster_code-intelligence.yaml
acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/container.cnrm.cloud.google.com_v1beta1_containernodepool_code-intelligence-cpu-pool-v1.yaml

Resolves #
**Checklist:**
1. `cd aws`

chore(gcp): migrate to e2 machine type attemp 2

---

aws/Doc/onboarding.md

Resolves #
Update onboarding doc to not configure webhook anymore, since we have configured organization-level webhook.
**Checklist:**
1. `cd aws`

Update onboarding doc

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml

Resolves #
Increase echo-test from 1d to 1s
**Checklist:**
1. `cd aws`

Increase echo-test from 1d to 1s

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml

Resolves #
Decrease echo-test from 1s to 1d
**Checklist:**
1. `cd aws`

Decrease echo-test from 1s to 1d

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/echo-helloworld.yaml
aws/Makefile
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/echo-helloworld.yaml

Resolves #
Add optional-test-infra-tekton resources
**Checklist:**
1. `cd aws`

Add optional-test-infra-tekton resources

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml

Part of https://github.com/kubeflow/testing/issues/861
Pushed the worker image to public ECR for pulling. 
**Checklist:**
1. `cd aws`

Enable pytorch

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
py/kubeflow/testing/run_e2e_workflow.py

See if this can help https://github.com/kubeflow/pytorch-operator/pull/316#issuecomment-767193878
**Checklist:**
1. `cd aws`

Set aws_argo_cluster_endpoint read from command-line parameter

---

py/kubeflow/testing/run_e2e_workflow.py

Resolves #
**Checklist:**
1. `cd aws`

Revert #871

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml

Help https://github.com/kubeflow/pytorch-operator/pull/316#issuecomment-767206693
**Checklist:**
1. `cd aws`

Use pre-built image for experimenting

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml

Update to latest tag test-worker image
**Checklist:**
1. `cd aws`

Update to latest image

---

aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml

Helps kubeflow/testing#861
Migrate manifests repo to new test-infra
**Checklist:**
1. `cd aws`

Migrate kubeflow/manifests

---

aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml

Helps https://github.com/kubeflow/testing/issues
Migrate kfctl repo to new test-infra
**Checklist:**
1. `cd aws`

Migrate kfctl repo

---

aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml

Helps https://github.com/kubeflow/testing/issues/861
Migrate kubeflow/katib repo to new test-infra
**Checklist:**
1. `cd aws`

Migrate katib repo

---

aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml

Helps https://github.com/kubeflow/testing/issues/861
Migrate kubeflow/kubeflow to new test-infra
**Checklist:**
1. `cd aws`

Migrate kubeflow/kubeflow repo

---

aws/GitOps/clusters/optional-test-infra-daily-worker/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-daily-worker/namespaces/prow/configmap/config.yaml

Resolves #
Update daily worker config
**Checklist:**
1. `cd aws`

Update daily worker config

---

aws/Access/assume-role-access/infra-viewer/trust-policy.json
aws/GitOps/clusters/optional-test-infra-daily-worker/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-daily-worker/namespaces/prow/configmap/config.yaml

Resolves #
Create periodic job for infra-viewer access sync
**Checklist:**
1. `cd aws`

Create periodic job for infra-viewer access sync

---

aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/secret.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml

Resolves #
Roll back self-managed repo test
**Checklist:**
1. `cd aws`

Roll back self-managed repo test

---

README.md

Resolves #
Add * instead of number
**Checklist:**
1. `cd aws`

Add * instead of number

---

aws/Access/assume-role-access/infra-viewer/trust-policy.json

Allow to my AWS account to assume the infra-viewer role
**Checklist:**
1. `cd aws`

add theofpa as infra-viewer

---

aws/Access/README.md
aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml

Resolves #861 
Migrate tf-operator to new test-infra
**Checklist:**
1. `cd aws`

Migrate tf-operator to new test-infra

---

.github/pull_request_template.md
aws/Makefile

Resolves #
1. Improve PR template to check if file differ
2. Improve self-check process
**Checklist:**
1. `cd aws`

[AWS] Improve self-check process

---

aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/kaniko.yaml
aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/kaniko.yaml

Add the caching option in kaniko task to have the build tasks running faster
**Checklist:**
1. `cd aws`

Kaniko cache

---

OWNERS

chore: Update OWNERS, add new team members

---

test-infra/kfp/endpoint

Resolves #
updated kfp endpoint to production. This is a PR related with https://github.com/kubeflow/testing/pull/907
**Checklist:**
1. `cd aws`

updated kfp endpoint to production

---

acm-repos/kf-ci-management/namespaces/kfp-ci/iam.yaml
test-infra/kfp/iam/iam.yaml

test(kfp): add access permission for kf-ci-v1-prow@kubeflow-ci.iam.gserviceaccount.com

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/kfp-standalone-1/kustomize/instance/proxy-agent-patch.yaml

Resolves #
changed back to staging proxy
**Checklist:**
1. `cd aws`

changed back to staging proxy

---

test-infra/kfp/endpoint

Resolves #
updated endpoint back to staging
Related to https://github.com/kubeflow/testing/pull/911
**Checklist:**
1. `cd aws`

updated endpoint back to staging

---

acm-repos/kf-ci-management/namespaces/kfp-ci/iam.yaml
test-infra/kfp/endpoint
test-infra/kfp/iam/iam.yaml

Resolves #
change access permission for kf-ci-v1-prow@kubeflow-ci.iam.gserviceaccount.com
**Checklist:**
1. `cd aws`

test(kfp): change access permission for kf-ci-v1-prow@kubeflow-ci.iam.gserviceaccount.com

---

aws/IaC/CDK/test-infra/config/static_config/ECR_Resources.py

Resolves #
Fix formatting issue
/cc @andreyvelich 
**Checklist:**
1. `cd aws`

Fix formatting issue

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml

Resolves #
Add kubeflow/kubeflow postsubmit job
**Checklist:**
1. `cd aws`

Add kubeflow/kubeflow postsubmit job

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml

Resolves #
Add periodic prowjobs for aws IAM role sync
**Checklist:**
1. `cd aws`

Add periodic prowjobs for aws IAM role sync

---

aws/GitOps/clusters/optional-test-infra-daily-worker/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-daily-worker/namespaces/prow/configmap/config.yaml

Resolves #
Disable daily-worker
**Checklist:**
1. `cd aws`

Disable daily-worker

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml

See: https://github.com/kubeflow/kubeflow/pull/5776#issuecomment-806783832
/assign @PatrickXYS

aws optional-test-infra: Enable tests for v1.3-branch of kubeflow/kubeflow

---

images/checkout_repos.sh

Helps https://github.com/kubeflow/kubeflow/issues/5784
Add PULL_BASE_REF for checking out repos script
**Checklist:**
1. `cd aws`

Add PULL_BASE_REF for checking out repos

---

images/checkout_repos.sh

Resolves #
[Follow Up] Add PULL_BASE_REF for checking out repos
**Checklist:**
1. `cd aws`

[Follow Up] Add PULL_BASE_REF for checking out repos

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml

Resolves #940
Fix postsubmit PR link
**Checklist:**
1. `cd aws`

Fix postsubmit PR link

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml

Resolves #
[FollowUp] Fix postsubmit PR link
**Checklist:**
1. `cd aws`

[FollowUp] Fix postsubmit PR link

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/kfp-standalone-1/kustomize/instance/kfp-s3-secret.yaml
test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml

Resolves #
added kfp-s3-secret to kfp-standalone-1
**Checklist:**
1. `cd aws`

added kfp-s3-secret to kfp-standalone-1

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/kfp-standalone-1/kustomize/instance/kfp-s3-secret.yaml
test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml

Resolves #
remove unused kfp s3 secret
**Checklist:**
1. `cd aws`

remove unused kfp s3 secret

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

updated kfp cluster to v1.7.0-alpha.3
**Checklist:**
1. `cd aws`

updated kfp cluster to v1.7.0-alpha.3

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml

Resolves #
This is for testing purpose in kserve github org.
**Checklist:**
1. `cd aws`

Add kserve for testing

---

aws/Access/assume-role-access/infra-viewer/trust-policy.json

I need to debug post-submit job failures for tf-operator repo
**Checklist:**
1. `cd aws`

Add Jiaxin account to test-infra-viewer

---

aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml

Related: https://github.com/kubeflow/katib/issues/1597.
I allow tests on Katib release-0.12 branch
/assign @PatrickXYS 
/cc @gaocegege @johnugeorge 
**Checklist:**
1. `cd aws`

Allow test on Katib release-0.12 branch

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/instance/workflow-controller-configmap-patch.yaml

test(kfp): use emissary executor

---

images/OWNERS

I'm no longer reviewing this code.
Resolves #
**Checklist:**
1. `cd aws`

Remove jlewi from images/OWNERs

---

acm-repos/kfp-standalone-1/kfp-all.yaml

Update kfp-all.yaml following: https://github.com/kubeflow/testing/pull/980 
1. `cd aws`

test(kfp): update kfp-all.yaml

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/cloudsql-proxy/cloudsql-proxy-deployment.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Resolves #
**Checklist:**
1. `cd aws`

test(kfp): Upgrade to 1.8.0-rc.2

---

acm-repos/kfp-standalone-1/kfp-all.yaml

Resolves #
Running `make kfp-update`
**Checklist:**
1. `cd aws`

pipelines: remove status by running kfp-update

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Resolves #
**Checklist:**
1. `cd aws`

test(kfp): Upgrade to 1.8.0-rc.3

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/pipelines-profile-controller/composite-controller.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Resolves #
**Checklist:**
1. `cd aws`

test(kfp): Upgrade to 1.8.0

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Resolves #
**Checklist:**
1. `cd aws`

test(kfp): Upgrade to 1.8.1

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/OWNERS
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/pipelines-profile-controller/sync.py
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/pipelines-profile-controller/test_sync.py
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Resolves #
**Checklist:**
1. `cd aws`

test(kfp): Upgrade to 2.0.0-alpha.0

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Resolves #
**Checklist:**
1. `cd aws`

test(kfp): Upgrade to 2.0.0-alpha.1

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Resolves #
**Checklist:**
1. `cd aws`

test(kfp): Upgrade to 2.0.0-alpha.2

---

aws/IaC/CDK/test-infra/config/static_config/ECR_Resources.py

Related: https://github.com/kubeflow/katib/pull/1833
Add PBT suggestion and test images to ECR.
**Checklist:**
1. `cd aws`

Add PBT images to katib ECR list

---

test-infra/kfp/Makefile

Resolves #
**Checklist:**
1. `cd aws`

test(kfp): Upgrade to 1.8.2

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/persistence-agent/cluster-role.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/persistence-agent/deployment-patch.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/persistence-agent/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/persistence-agent/params.env
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/view-edit-cluster-roles.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/ml-pipeline-persistenceagent-role.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Upgrading KFP test-infra to v 2.0.0-alpha.4
**Checklist:**
1. `cd aws`

Upgrade to kfp 2.0.0-alpha.4

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Resolves #
**Checklist:**
1. `cd aws`

Upgrade to kfp 2.0.0-alpha.5

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/cache-deployment.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/third-party/mysql/base/mysql-deployment.yaml

Resolves #
Upgrade test infra for release 2.0.0-alpha.6
**Checklist:**
1. `cd aws`

Update to kfp 2.0.0-alpha.6

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/cache-deployment.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/platform-agnostic-multi-user-pns/workflow-controller-configmap-patch.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/platform-agnostic-pns/workflow-controller-configmap-patch.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/third-party/mysql/base/mysql-deployment.yaml

Resolves #
**Checklist:**
1. `cd aws`

Update manifest to 2.0.0-beta.0. Closes #8697

---

acm-repos/kfp-standalone-1/kfp-all.yaml

Update kfp test infra to 2.0.0-rc.1

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Resolves #
**Checklist:**
1. `cd aws`

Update kfp test infra to using kfp 2.0

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/persistence-agent/cluster-role.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/ml-pipeline-persistenceagent-role.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Resolves #
**Checklist:**
1. `cd aws`

Update kfp test infra to using kfp 2.0.1

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml

Resolves #
**Checklist:**
1. `cd aws`

Update KFP test infra to using KFP 2.0.3

---

acm-repos/kfp-standalone-1/kfp-all.yaml
test-infra/kfp/Makefile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml
test-infra/kfp/kfp-standalone-1/kustomize/upstream/third-party/application/application-controller-deployment.yaml

Resolves #
**Checklist:**
1. `cd aws`

Update KFP test infra to using KFP 2.0.5
